export {
  EOG_2D_PACKAGE_ID as EOG_2D_DESIGNER_PACKAGE_ID,
  EOG_2D_DESIGNER_FEATURE_ID,
  EOG_2D_DESIGNER_CAPABILITY,
  EOG_2D_DESIGNER_EXPERIENCE_ID,
  EOG_2D_DESIGNER_PAGE_ID,
  EOG_2D_DESIGNER_PAGE_SOURCE,
  EOG_2D_DESIGNER_ROUTE,
  eog2dPackage as eog2dDesignerPackage
} from "../eog-2d/package.js";
