export const appPlatformLocalizationBundles = [
  {
    contractVersion: "0.1.0" as const,
    namespace: "evo-app-platform",
    locale: "en",
    messages: {
      "navigation.evo-plugin-store.nav.label": "Plugin Store",
      "catalog.evo.plugin-store.title": "EVO Plugin Store",
      "catalog.evo.plugin-store.description": "Discover, install and manage EVO plugins.",
      "catalog.evo.plugin-store.item.summary": "{features} feature(s) · {providedCapabilities} provided capability(ies) · {requiredCapabilities} required capability(ies)",
      "catalog.evo.plugin-store.status.not-installed.label": "Not installed",
      "catalog.evo.plugin-store.status.enabled.label": "Enabled",
      "catalog.evo.plugin-store.status.disabled.label": "Disabled",
      "catalog.evo.plugin-store.action.install.label": "Install",
      "catalog.evo.plugin-store.action.install.help": "The system automatically checks dependencies and compatibility. Human input is requested only when a material decision is required.",
      "catalog.evo.plugin-store.action.plan.label": "Installation details",
      "catalog.evo.plugin-store.action.plan.help": "Optional: preview dependencies, packages to install, and features to activate.",
      "catalog.evo.plugin-store.action.open.label": "Open",
      "catalog.evo.plugin-store.action.disable.label": "Disable",
      "catalog.evo.plugin-store.action.uninstall.label": "Uninstall",
      "catalog.evo.plugin-store.action.enable.label": "Enable",
      "catalog.evo.plugin-store.action.configure.label": "Configure",
      "workbench.activity.apps": "Apps",
      "workbench.activity.plugins": "Plugins",
      "workbench.activity.workspace": "Workspace",
      "workbench.activity.settings": "Settings",
      "catalog.evo.settings.title": "Settings",
      "catalog.evo.settings.description": "Configure installed plugins that expose standard settings.",
      "catalog.evo.settings.empty": "No installed plugins expose standard settings.",
      "catalog.evo.settings.action.configure.label": "Configure"
    }
  },
  {
    contractVersion: "0.1.0" as const,
    namespace: "evo-app-platform",
    locale: "zh-CN",
    messages: {
      "navigation.evo-plugin-store.nav.label": "插件商店",
      "catalog.evo.plugin-store.title": "EVO 插件商店",
      "catalog.evo.plugin-store.description": "发现、安装和管理 EVO 插件。",
      "catalog.evo.plugin-store.item.summary": "{features} 个 Feature · 提供 {providedCapabilities} 个 Capability · 依赖 {requiredCapabilities} 个 Capability",
      "catalog.evo.plugin-store.status.not-installed.label": "未安装",
      "catalog.evo.plugin-store.status.enabled.label": "已启用",
      "catalog.evo.plugin-store.status.disabled.label": "已禁用",
      "catalog.evo.plugin-store.action.install.label": "安装",
      "catalog.evo.plugin-store.action.install.help": "系统自动检查依赖和兼容性；只有需要人类判断的重要事项才会要求确认。",
      "catalog.evo.plugin-store.action.plan.label": "安装详情",
      "catalog.evo.plugin-store.action.plan.help": "可选：预览依赖、将安装的 Package 和将激活的 Feature。",
      "catalog.evo.plugin-store.action.open.label": "打开",
      "catalog.evo.plugin-store.action.disable.label": "禁用",
      "catalog.evo.plugin-store.action.uninstall.label": "卸载",
      "catalog.evo.plugin-store.action.enable.label": "启用",
      "catalog.evo.plugin-store.action.configure.label": "配置",
      "workbench.activity.apps": "应用",
      "workbench.activity.plugins": "插件",
      "workbench.activity.workspace": "工作区",
      "workbench.activity.settings": "设置",
      "catalog.evo.settings.title": "设置",
      "catalog.evo.settings.description": "配置已安装且声明标准设置项的插件。",
      "catalog.evo.settings.empty": "当前没有已安装插件提供标准设置。",
      "catalog.evo.settings.action.configure.label": "配置"
    }
  }
];
