export const appPlatformLocalizationBundles = [
  {
    contractVersion: "0.1.0" as const,
    namespace: "evo-app-platform",
    locale: "en",
    messages: {
      "navigation.evo-plugin-store.nav.label": "Plugins",
      "extensions.evo.plugin-store.title": "EVO Plugin Platform",
      "extensions.evo.plugin-store.description": "Install and manage extensions through the stable Plugin Protocol. App Platform owns lifecycle; Eidos renders declared contribution points.",
      "extensions.evo.plugin-store.status.not-installed.label": "Not installed",
      "extensions.evo.plugin-store.status.enabled.label": "Enabled",
      "extensions.evo.plugin-store.status.disabled.label": "Disabled",
      "extensions.evo.plugin-store.status.incompatible.label": "Incompatible",
      "extensions.evo.plugin-store.action.install.label": "Install",
      "extensions.evo.plugin-store.action.install.help": "Dependencies and compatibility are checked automatically.",
      "extensions.evo.plugin-store.action.plan.label": "Details",
      "extensions.evo.plugin-store.action.plan.help": "Inspect dependency and activation plan.",
      "extensions.evo.plugin-store.action.open.label": "Open",
      "extensions.evo.plugin-store.action.disable.label": "Disable",
      "extensions.evo.plugin-store.action.uninstall.label": "Uninstall",
      "extensions.evo.plugin-store.action.enable.label": "Enable",
      "extensions.evo.plugin-store.action.configure.label": "Configure",
      "extensions.evo.plugin-store.action.setup.label": "Set up",
      "extensions.evo.plugin-store.readiness.ready.label": "Ready",
      "extensions.evo.plugin-store.readiness.ready.message": "Personal Agent is ready.",
      "extensions.evo.plugin-store.readiness.setup-required.label": "Needs setup",
      "extensions.evo.plugin-store.readiness.setup-required.message": "Complete Provider setup before opening Personal Agent.",
      "extensions.evo.plugin-store.readiness.degraded.label": "Degraded",
      "extensions.evo.plugin-store.readiness.degraded.message": "Personal Agent can open, but the selected LLM Provider is degraded.",
      "extensions.evo.plugin-store.readiness.error.label": "Unavailable",
      "extensions.evo.plugin-store.readiness.error.message": "Personal Agent cannot currently use the selected LLM Provider.",
      "catalog.evo.plugin-store.title": "EVO Plugin Store",
      "catalog.evo.plugin-store.description": "Discover, install and manage EVO plugins.",
      "catalog.evo.plugin-store.item.summary": "{features} feature(s) · {providedCapabilities} provided capability(ies) · {requiredCapabilities} required capability(ies)",
      "catalog.evo.plugin-store.status.not-installed.label": "Not installed",
      "catalog.evo.plugin-store.status.enabled.label": "Enabled",
      "catalog.evo.plugin-store.status.disabled.label": "Disabled",
      "catalog.evo.plugin-store.action.install.label": "Install",
      "catalog.evo.plugin-store.action.install.help": "The system automatically checks dependencies and compatibility. Human input is requested only when a material decision is required.",
      "catalog.evo.plugin-store.action.plan.label": "Installation details",
      "catalog.evo.plugin-store.action.plan.help": "Optional: preview dependencies, packages to install, and features to activate.",
      "catalog.evo.plugin-store.action.open.label": "Open",
      "catalog.evo.plugin-store.action.disable.label": "Disable",
      "catalog.evo.plugin-store.action.uninstall.label": "Uninstall",
      "catalog.evo.plugin-store.action.enable.label": "Enable",
      "catalog.evo.plugin-store.action.configure.label": "Configure",
      "workbench.activity.apps": "Apps",
      "workbench.activity.plugins": "Plugins",
      "workbench.activity.workspace": "Workspace",
      "workbench.activity.help": "Help",
      "workbench.activity.settings": "Settings",
      "workbench.activity.memory": "Memory",
      "catalog.evo.memory.governance.title": "Memory Governance",
      "catalog.evo.memory.governance.description": "Review retention, privacy classification, legal hold and scheduled operation state for the active Context.",
      "catalog.evo.memory.governance.empty": "No Memory exists in this Context.",
      "catalog.evo.memory.governance.search.placeholder": "Filter governed Memory",
      "catalog.evo.memory.governance.search.ariaLabel": "Filter governed Memory",
      "catalog.evo.memory.governance.search.noResults": "No governed Memory matches this filter.",
      "catalog.evo.memory.search.title": "Memory Search",
      "catalog.evo.memory.search.description": "Search the Host-authorized Memory set for the active Context.",
      "catalog.evo.memory.search.empty": "No visible Memory is available in this Context.",
      "catalog.evo.memory.search.search.placeholder": "Search visible Memory",
      "catalog.evo.memory.search.search.ariaLabel": "Search visible Memory",
      "catalog.evo.memory.search.search.noResults": "No visible Memory matches this search.",
      "catalog.evo.memory.sources.title": "Memory Source Health",
      "catalog.evo.memory.sources.description": "Operational health for Memory retrieval, governance, DLP, semantic ranking and intake Providers.",
      "catalog.evo.memory.sources.empty": "No effective Memory Providers are active.",
      "catalog.evo.memory.retention-simulation.title": "Retention Simulation",
      "catalog.evo.memory.retention-simulation.description": "Dry-run retention impact without changing Memory or governance state.",
      "catalog.evo.memory.retention-simulation.empty": "No Memory exists in this Context.",
      "catalog.evo.help.title": "Help",
      "catalog.evo.help.description": "Search authoritative product Help. Results follow the active locale with deterministic fallback.",
      "catalog.evo.help.empty": "No Help documents are available.",
      "catalog.evo.help.search.placeholder": "Search help…",
      "catalog.evo.help.search.ariaLabel": "Search Help",
      "catalog.evo.help.search.noResults": "No matching Help documents.",
      "catalog.evo.help.action.open.label": "Open",
      "catalog.evo.settings.title": "Settings",
      "catalog.evo.settings.description": "Configure installed plugins that expose standard settings.",
      "catalog.evo.settings.empty": "No installed plugins expose standard settings.",
      "catalog.evo.settings.action.configure.label": "Configure"
    }
  },
  {
    contractVersion: "0.1.0" as const,
    namespace: "evo-app-platform",
    locale: "zh-CN",
    messages: {
      "navigation.evo-plugin-store.nav.label": "插件",
      "extensions.evo.plugin-store.title": "EVO 插件平台",
      "extensions.evo.plugin-store.description": "通过稳定的插件协议安装和管理扩展。App Platform 负责生命周期，Eidos 渲染插件声明的 Contribution Points。",
      "extensions.evo.plugin-store.status.not-installed.label": "未安装",
      "extensions.evo.plugin-store.status.enabled.label": "已启用",
      "extensions.evo.plugin-store.status.disabled.label": "已禁用",
      "extensions.evo.plugin-store.status.incompatible.label": "不兼容",
      "extensions.evo.plugin-store.action.install.label": "安装",
      "extensions.evo.plugin-store.action.install.help": "系统会自动检查依赖和兼容性。",
      "extensions.evo.plugin-store.action.plan.label": "详情",
      "extensions.evo.plugin-store.action.plan.help": "查看依赖和激活计划。",
      "extensions.evo.plugin-store.action.open.label": "打开",
      "extensions.evo.plugin-store.action.disable.label": "禁用",
      "extensions.evo.plugin-store.action.uninstall.label": "卸载",
      "extensions.evo.plugin-store.action.enable.label": "启用",
      "extensions.evo.plugin-store.action.configure.label": "配置",
      "extensions.evo.plugin-store.action.setup.label": "设置",
      "extensions.evo.plugin-store.readiness.ready.label": "就绪",
      "extensions.evo.plugin-store.readiness.ready.message": "个人代理已就绪。",
      "extensions.evo.plugin-store.readiness.setup-required.label": "需要设置",
      "extensions.evo.plugin-store.readiness.setup-required.message": "打开个人代理前，请先完成 Provider 设置。",
      "extensions.evo.plugin-store.readiness.degraded.label": "性能下降",
      "extensions.evo.plugin-store.readiness.degraded.message": "个人代理仍可打开，但当前 LLM Provider 处于降级状态。",
      "extensions.evo.plugin-store.readiness.error.label": "不可用",
      "extensions.evo.plugin-store.readiness.error.message": "个人代理当前无法使用已选择的 LLM Provider。",
      "catalog.evo.plugin-store.title": "EVO 插件商店",
      "catalog.evo.plugin-store.description": "发现、安装和管理 EVO 插件。",
      "catalog.evo.plugin-store.item.summary": "{features} 个 Feature · 提供 {providedCapabilities} 个 Capability · 依赖 {requiredCapabilities} 个 Capability",
      "catalog.evo.plugin-store.status.not-installed.label": "未安装",
      "catalog.evo.plugin-store.status.enabled.label": "已启用",
      "catalog.evo.plugin-store.status.disabled.label": "已禁用",
      "catalog.evo.plugin-store.action.install.label": "安装",
      "catalog.evo.plugin-store.action.install.help": "系统自动检查依赖和兼容性；只有需要人类判断的重要事项才会要求确认。",
      "catalog.evo.plugin-store.action.plan.label": "安装详情",
      "catalog.evo.plugin-store.action.plan.help": "可选：预览依赖、将安装的 Package 和将激活的 Feature。",
      "catalog.evo.plugin-store.action.open.label": "打开",
      "catalog.evo.plugin-store.action.disable.label": "禁用",
      "catalog.evo.plugin-store.action.uninstall.label": "卸载",
      "catalog.evo.plugin-store.action.enable.label": "启用",
      "catalog.evo.plugin-store.action.configure.label": "配置",
      "workbench.activity.apps": "应用",
      "workbench.activity.plugins": "插件",
      "workbench.activity.workspace": "工作区",
      "workbench.activity.help": "帮助",
      "workbench.activity.settings": "设置",
      "workbench.activity.memory": "记忆",
      "catalog.evo.memory.governance.title": "记忆治理",
      "catalog.evo.memory.governance.description": "查看当前 Context 的保留策略、隐私分类、Legal Hold 与定时操作状态。",
      "catalog.evo.memory.governance.empty": "当前 Context 没有 Memory。",
      "catalog.evo.memory.governance.search.placeholder": "筛选受治理 Memory",
      "catalog.evo.memory.governance.search.ariaLabel": "筛选受治理 Memory",
      "catalog.evo.memory.governance.search.noResults": "没有符合筛选条件的 Memory。",
      "catalog.evo.memory.search.title": "记忆搜索",
      "catalog.evo.memory.search.description": "搜索 Host 已授权且属于当前 Context 的 Memory。",
      "catalog.evo.memory.search.empty": "当前 Context 没有可见 Memory。",
      "catalog.evo.memory.search.search.placeholder": "搜索可见 Memory",
      "catalog.evo.memory.search.search.ariaLabel": "搜索可见 Memory",
      "catalog.evo.memory.search.search.noResults": "没有匹配的可见 Memory。",
      "catalog.evo.memory.sources.title": "记忆来源健康状态",
      "catalog.evo.memory.sources.description": "查看 Memory 检索、治理、DLP、语义排序与 Intake Provider 的运行状态。",
      "catalog.evo.memory.sources.empty": "当前没有生效的 Memory Provider。",
      "catalog.evo.memory.retention-simulation.title": "保留策略模拟",
      "catalog.evo.memory.retention-simulation.description": "预演保留策略影响，不修改 Memory 或治理状态。",
      "catalog.evo.memory.retention-simulation.empty": "当前 Context 没有 Memory。",
      "catalog.evo.help.title": "帮助",
      "catalog.evo.help.description": "搜索权威产品帮助。结果会跟随当前语言，并按确定性规则回退。",
      "catalog.evo.help.empty": "当前没有可用的帮助文档。",
      "catalog.evo.help.search.placeholder": "搜索帮助…",
      "catalog.evo.help.search.ariaLabel": "搜索帮助",
      "catalog.evo.help.search.noResults": "没有匹配的帮助内容。",
      "catalog.evo.help.action.open.label": "打开",
      "catalog.evo.settings.title": "设置",
      "catalog.evo.settings.description": "配置已安装且声明标准设置项的插件。",
      "catalog.evo.settings.empty": "当前没有已安装插件提供标准设置。",
      "catalog.evo.settings.action.configure.label": "配置"
    }
  }
,
  {
    contractVersion: "0.1.0" as const,
    namespace: "evo-app-platform",
    locale: "ja",
    messages: {
      "extensions.evo.plugin-store.action.setup.label": "セットアップ",
      "extensions.evo.plugin-store.readiness.ready.label": "準備完了",
      "extensions.evo.plugin-store.readiness.ready.message": "パーソナルエージェントを利用できます。",
      "extensions.evo.plugin-store.readiness.setup-required.label": "セットアップが必要",
      "extensions.evo.plugin-store.readiness.setup-required.message": "パーソナルエージェントを開く前に Provider の設定を完了してください。",
      "extensions.evo.plugin-store.readiness.degraded.label": "低下",
      "extensions.evo.plugin-store.readiness.degraded.message": "パーソナルエージェントは開けますが、選択した LLM Provider は低下状態です。",
      "extensions.evo.plugin-store.readiness.error.label": "利用不可",
      "extensions.evo.plugin-store.readiness.error.message": "パーソナルエージェントは現在、選択した LLM Provider を利用できません。",
      "workbench.activity.memory": "メモリ",
      "catalog.evo.memory.governance.title": "メモリガバナンス",
      "catalog.evo.memory.governance.description": "現在の Context の保持ポリシー、プライバシー分類、Legal Hold、定期処理の状態を確認します。",
      "catalog.evo.memory.governance.empty": "この Context には Memory がありません。",
      "catalog.evo.memory.search.title": "メモリ検索",
      "catalog.evo.memory.search.description": "現在の Context で Host が許可した Memory を検索します。",
      "catalog.evo.memory.search.empty": "この Context には表示可能な Memory がありません。",
      "catalog.evo.memory.sources.title": "メモリソースの状態",
      "catalog.evo.memory.sources.description": "Memory の検索、ガバナンス、DLP、セマンティックランキング、Intake Provider の稼働状態です。",
      "catalog.evo.memory.sources.empty": "有効な Memory Provider はありません。",
      "catalog.evo.memory.retention-simulation.title": "保持ポリシーシミュレーション",
      "catalog.evo.memory.retention-simulation.description": "Memory やガバナンス状態を変更せずに保持ポリシーの影響を確認します。",
      "catalog.evo.memory.retention-simulation.empty": "この Context には Memory がありません。",
    }
  },
  {
    contractVersion: "0.1.0" as const,
    namespace: "evo-app-platform",
    locale: "zh-TW",
    messages: {
      "extensions.evo.plugin-store.action.setup.label": "設定",
      "extensions.evo.plugin-store.readiness.ready.label": "就緒",
      "extensions.evo.plugin-store.readiness.ready.message": "個人代理已就緒。",
      "extensions.evo.plugin-store.readiness.setup-required.label": "需要設定",
      "extensions.evo.plugin-store.readiness.setup-required.message": "開啟個人代理前，請先完成 Provider 設定。",
      "extensions.evo.plugin-store.readiness.degraded.label": "效能下降",
      "extensions.evo.plugin-store.readiness.degraded.message": "個人代理仍可開啟，但目前 LLM Provider 處於降級狀態。",
      "extensions.evo.plugin-store.readiness.error.label": "無法使用",
      "extensions.evo.plugin-store.readiness.error.message": "個人代理目前無法使用已選擇的 LLM Provider。",
      "workbench.activity.memory": "記憶",
      "catalog.evo.memory.governance.title": "記憶治理",
      "catalog.evo.memory.governance.description": "檢視目前 Context 的保留政策、隱私分類、Legal Hold 與排程操作狀態。",
      "catalog.evo.memory.governance.empty": "目前 Context 沒有 Memory。",
      "catalog.evo.memory.search.title": "記憶搜尋",
      "catalog.evo.memory.search.description": "搜尋 Host 已授權且屬於目前 Context 的 Memory。",
      "catalog.evo.memory.search.empty": "目前 Context 沒有可見 Memory。",
      "catalog.evo.memory.sources.title": "記憶來源健康狀態",
      "catalog.evo.memory.sources.description": "檢視 Memory 檢索、治理、DLP、語意排序與 Intake Provider 的執行狀態。",
      "catalog.evo.memory.sources.empty": "目前沒有生效的 Memory Provider。",
      "catalog.evo.memory.retention-simulation.title": "保留政策模擬",
      "catalog.evo.memory.retention-simulation.description": "預演保留政策影響，不修改 Memory 或治理狀態。",
      "catalog.evo.memory.retention-simulation.empty": "目前 Context 沒有 Memory。",
    }
  }
,
  {
    contractVersion: "0.1.0" as const,
    namespace: "provider-binding:llm.inference",
    locale: "en",
    messages: {
      "settings.title": "AI service",
      "settings.description": "Choose the installed AI service Personal Agent should use. Advanced scope and runtime details are available when needed.",
      "settings.saveLabel": "Save choice",
      "settings.providerId.label": "Service",
      "settings.providerId.description": "The AI service Personal Agent will use.",
      "settings.scope.label": "Scope",
      "settings.scope.description": "More specific scopes override broader scopes.",
      "settings.scopeId.label": "Scope ID",
      "settings.scopeId.description": "Required outside SYSTEM scope.",
      "settings.priority.label": "Priority",
      "settings.priority.description": "Tie-breaker within the same scope specificity.",
      "settings.adminToken.label": "Administrator authorization",
      "settings.adminToken.description": "Used only to authenticate the administrator. It is never persisted in Provider binding state.",
      "settings.currentResolution.label": "Current resolution",
      "settings.selectedHealth.label": "Selected runtime health",
      "settings.notice.title": "Connection status",
      "settings.group.selection.title": "AI service",
      "settings.group.selection.description": "Choose the service Personal Agent should use.",
      "settings.group.scope.title": "Advanced scope",
      "settings.group.scope.description": "More specific scopes override broader scopes. Priority only breaks ties at the same specificity.",
      "settings.group.runtime-status.title": "Runtime diagnostics",
      "settings.group.runtime-status.description": "Host-observed resolution and health for the selected Provider.",
      "settings.group.administration.title": "Administrator authorization",
      "settings.group.administration.description": "Authorization used only when changing a protected Provider binding.",
      "settings.scope.option.SYSTEM": "System default",
      "settings.scope.option.INSTALLATION": "This installation",
      "settings.scope.option.ENTERPRISE": "Enterprise",
      "settings.scope.option.COMPANY": "Company",
      "settings.scope.option.WORKSPACE": "Workspace",
      "settings.scope.option.USER": "User",
    }
  },
  {
    contractVersion: "0.1.0" as const,
    namespace: "provider-binding:llm.inference",
    locale: "zh-CN",
    messages: {
      "settings.title": "AI 服务",
      "settings.description": "选择个人代理要使用的已安装 AI 服务。作用范围和运行诊断等专业选项可在高级设置中查看。",
      "settings.saveLabel": "保存选择",
      "settings.providerId.label": "服务",
      "settings.providerId.description": "个人代理将使用的 AI 服务。",
      "settings.scope.label": "作用域",
      "settings.scope.description": "更具体的作用域会覆盖更宽泛的作用域。",
      "settings.scopeId.label": "作用域 ID",
      "settings.scopeId.description": "除 SYSTEM 作用域外均需要填写。",
      "settings.priority.label": "优先级",
      "settings.priority.description": "仅用于同一作用域层级内的顺序判定。",
      "settings.adminToken.label": "管理员授权",
      "settings.adminToken.description": "仅用于验证管理员身份，不会持久化到 Provider 绑定状态。",
      "settings.currentResolution.label": "当前解析结果",
      "settings.selectedHealth.label": "已选择运行时健康状态",
      "settings.notice.title": "连接状态",
      "settings.group.selection.title": "AI 服务",
      "settings.group.selection.description": "选择个人代理要使用的服务。",
      "settings.group.scope.title": "高级作用范围",
      "settings.group.scope.description": "更具体的作用域覆盖更宽泛的作用域；优先级仅用于相同作用域层级的并列判定。",
      "settings.group.runtime-status.title": "运行诊断",
      "settings.group.runtime-status.description": "Host 实际观测的 Provider 解析结果与健康状态。",
      "settings.group.administration.title": "管理员授权",
      "settings.group.administration.description": "仅在修改受保护的 Provider 绑定时使用的授权。",
      "settings.scope.option.SYSTEM": "系统默认",
      "settings.scope.option.INSTALLATION": "当前安装",
      "settings.scope.option.ENTERPRISE": "企业",
      "settings.scope.option.COMPANY": "公司",
      "settings.scope.option.WORKSPACE": "工作区",
      "settings.scope.option.USER": "用户",
    }
  },
  {
    contractVersion: "0.1.0" as const,
    namespace: "provider-binding:llm.inference",
    locale: "ja",
    messages: {
      "settings.title": "AI サービス",
      "settings.description": "パーソナルエージェントが使用するインストール済み AI サービスを選択します。スコープやランタイム診断などの専門設定は詳細設定で確認できます。",
      "settings.saveLabel": "選択を保存",
      "settings.providerId.label": "サービス",
      "settings.providerId.description": "パーソナルエージェントが使用する AI サービス。",
      "settings.scope.label": "スコープ",
      "settings.scope.description": "より具体的なスコープが広いスコープより優先されます。",
      "settings.scopeId.label": "スコープ ID",
      "settings.scopeId.description": "SYSTEM 以外のスコープでは必須です。",
      "settings.priority.label": "優先度",
      "settings.priority.description": "同じスコープ詳細度でのみ使用する優先順位です。",
      "settings.adminToken.label": "管理者認証",
      "settings.adminToken.description": "管理者の認証にのみ使用され、Provider バインディング状態には保存されません。",
      "settings.currentResolution.label": "現在の解決結果",
      "settings.selectedHealth.label": "選択したランタイムの状態",
      "settings.notice.title": "接続状態",
      "settings.group.selection.title": "AI サービス",
      "settings.group.selection.description": "パーソナルエージェントが使用するサービスを選択します。",
      "settings.group.scope.title": "詳細スコープ",
      "settings.group.scope.description": "より具体的なスコープが優先され、優先度は同じ詳細度でのみ使用されます。",
      "settings.group.runtime-status.title": "ランタイム診断",
      "settings.group.runtime-status.description": "Host が観測した Provider の解決結果とヘルス状態です。",
      "settings.group.administration.title": "管理者認証",
      "settings.group.administration.description": "保護された Provider バインディングを変更する場合にのみ使用する認証です。",
      "settings.scope.option.SYSTEM": "システム既定",
      "settings.scope.option.INSTALLATION": "このインストール",
      "settings.scope.option.ENTERPRISE": "エンタープライズ",
      "settings.scope.option.COMPANY": "会社",
      "settings.scope.option.WORKSPACE": "ワークスペース",
      "settings.scope.option.USER": "ユーザー",
    }
  },
  {
    contractVersion: "0.1.0" as const,
    namespace: "provider-binding:llm.inference",
    locale: "zh-TW",
    messages: {
      "settings.title": "AI 服務",
      "settings.description": "選擇個人代理要使用的已安裝 AI 服務。作用範圍與執行診斷等專業選項可在進階設定中查看。",
      "settings.saveLabel": "儲存選擇",
      "settings.providerId.label": "服務",
      "settings.providerId.description": "個人代理將使用的 AI 服務。",
      "settings.scope.label": "作用域",
      "settings.scope.description": "較具體的作用域會覆蓋較寬泛的作用域。",
      "settings.scopeId.label": "作用域 ID",
      "settings.scopeId.description": "除 SYSTEM 作用域外皆需要填寫。",
      "settings.priority.label": "優先順序",
      "settings.priority.description": "僅用於相同作用域層級內的順序判定。",
      "settings.adminToken.label": "管理員授權",
      "settings.adminToken.description": "僅用於驗證管理員身分，不會持久化到 Provider 綁定狀態。",
      "settings.currentResolution.label": "目前解析結果",
      "settings.selectedHealth.label": "已選擇執行階段健康狀態",
      "settings.notice.title": "連接狀態",
      "settings.group.selection.title": "AI 服務",
      "settings.group.selection.description": "選擇個人代理要使用的服務。",
      "settings.group.scope.title": "進階作用範圍",
      "settings.group.scope.description": "較具體的作用域會覆蓋較寬泛的作用域；優先順序僅用於相同作用域層級。",
      "settings.group.runtime-status.title": "執行診斷",
      "settings.group.runtime-status.description": "Host 實際觀測的 Provider 解析結果與健康狀態。",
      "settings.group.administration.title": "管理員授權",
      "settings.group.administration.description": "僅在修改受保護的 Provider 綁定時使用的授權。",
      "settings.scope.option.SYSTEM": "系統預設",
      "settings.scope.option.INSTALLATION": "目前安裝",
      "settings.scope.option.ENTERPRISE": "企業",
      "settings.scope.option.COMPANY": "公司",
      "settings.scope.option.WORKSPACE": "工作區",
      "settings.scope.option.USER": "使用者",
    }
  }
];
