// Generated from jiangxng/bookkeeping src/main/resources/accounts.sql. Preserve source semantics; do not hand-edit.
export const bookkeepingAccounts = [
  {
    "id": 1001,
    "title": "库存现金",
    "isFinance": true,
    "bigClass": "资产类",
    "subClass": null,
    "description": null,
    "objectField": "资金编码",
    "objectType": "cash",
    "laneFields": "现金流项目",
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 1002,
    "title": "银行存款",
    "isFinance": true,
    "bigClass": "资产类",
    "subClass": null,
    "description": null,
    "objectField": "资金编码",
    "objectType": "cash",
    "laneFields": "现金流项目",
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 1012,
    "title": "其他货币资金",
    "isFinance": true,
    "bigClass": "资产类",
    "subClass": null,
    "description": null,
    "objectField": "资金编码",
    "objectType": "cash",
    "laneFields": "现金流项目",
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 1101,
    "title": "交易性金融资产",
    "isFinance": true,
    "bigClass": "资产类",
    "subClass": null,
    "description": null,
    "objectField": "其他核算编码",
    "objectType": "otherObject",
    "laneFields": null,
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 1102,
    "title": "衍生金融资产",
    "isFinance": true,
    "bigClass": "资产类",
    "subClass": null,
    "description": null,
    "objectField": "其他核算编码",
    "objectType": "otherObject",
    "laneFields": null,
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 1121,
    "title": "应收票据",
    "isFinance": true,
    "bigClass": "资产类",
    "subClass": null,
    "description": null,
    "objectField": "往来编码",
    "objectType": "dealer",
    "laneFields": "往来标签",
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 1122,
    "title": "应收账款",
    "isFinance": true,
    "bigClass": "资产类",
    "subClass": null,
    "description": null,
    "objectField": "往来编码",
    "objectType": "dealer",
    "laneFields": "往来标签",
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 1123,
    "title": "预付账款",
    "isFinance": true,
    "bigClass": "资产类",
    "subClass": null,
    "description": null,
    "objectField": "往来编码",
    "objectType": "dealer",
    "laneFields": "往来标签",
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 1131,
    "title": "应收股利",
    "isFinance": true,
    "bigClass": "资产类",
    "subClass": null,
    "description": null,
    "objectField": "往来编码",
    "objectType": "dealer",
    "laneFields": "往来标签",
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 1132,
    "title": "应收利息",
    "isFinance": true,
    "bigClass": "资产类",
    "subClass": null,
    "description": null,
    "objectField": "往来编码",
    "objectType": "dealer",
    "laneFields": "往来标签",
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 1221,
    "title": "其他应收款",
    "isFinance": true,
    "bigClass": "资产类",
    "subClass": null,
    "description": null,
    "objectField": "往来编码",
    "objectType": "dealer",
    "laneFields": "往来标签",
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 1231,
    "title": "坏账准备",
    "isFinance": true,
    "bigClass": "资产类",
    "subClass": null,
    "description": null,
    "objectField": "其他核算编码",
    "objectType": "otherObject",
    "laneFields": null,
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 1301,
    "title": "待摊费用",
    "isFinance": true,
    "bigClass": "资产类",
    "subClass": null,
    "description": null,
    "objectField": "其他核算编码",
    "objectType": "otherObject",
    "laneFields": null,
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 1401,
    "title": "材料采购",
    "isFinance": true,
    "bigClass": "资产类",
    "subClass": null,
    "description": null,
    "objectField": "其他核算编码",
    "objectType": "otherObject",
    "laneFields": null,
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 1402,
    "title": "在途物资",
    "isFinance": true,
    "bigClass": "资产类",
    "subClass": null,
    "description": null,
    "objectField": "其他核算编码",
    "objectType": "otherObject",
    "laneFields": null,
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 1403,
    "title": "原材料",
    "isFinance": true,
    "bigClass": "资产类",
    "subClass": null,
    "description": null,
    "objectField": "物料编码",
    "objectType": "material",
    "laneFields": "仓库编码",
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 1404,
    "title": "材料成本差异",
    "isFinance": true,
    "bigClass": "资产类",
    "subClass": null,
    "description": null,
    "objectField": "其他核算编码",
    "objectType": "otherObject",
    "laneFields": null,
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 1405,
    "title": "库存商品",
    "isFinance": true,
    "bigClass": "资产类",
    "subClass": null,
    "description": null,
    "objectField": "物料编码",
    "objectType": "material",
    "laneFields": "仓库编码",
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 1406,
    "title": "发出商品",
    "isFinance": true,
    "bigClass": "资产类",
    "subClass": null,
    "description": null,
    "objectField": "物料编码",
    "objectType": "material",
    "laneFields": "往来编码,往来标签",
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 1407,
    "title": "商品进销差价",
    "isFinance": true,
    "bigClass": "资产类",
    "subClass": null,
    "description": null,
    "objectField": "其他核算编码",
    "objectType": "otherObject",
    "laneFields": null,
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 1408,
    "title": "委托加工物资",
    "isFinance": true,
    "bigClass": "资产类",
    "subClass": null,
    "description": null,
    "objectField": "物料编码",
    "objectType": "material",
    "laneFields": "往来编码,仓库编码,往来标签",
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 1411,
    "title": "周转材料",
    "isFinance": true,
    "bigClass": "资产类",
    "subClass": null,
    "description": null,
    "objectField": "物料编码",
    "objectType": "material",
    "laneFields": "仓库编码",
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 1421,
    "title": "消耗性生物资产",
    "isFinance": true,
    "bigClass": "资产类",
    "subClass": null,
    "description": null,
    "objectField": "其他核算编码",
    "objectType": "otherObject",
    "laneFields": null,
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 1422,
    "title": "半成品",
    "isFinance": true,
    "bigClass": "资产类",
    "subClass": null,
    "description": null,
    "objectField": "物料编码",
    "objectType": "material",
    "laneFields": "仓库编码",
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 1423,
    "title": "在产品",
    "isFinance": true,
    "bigClass": "资产类",
    "subClass": null,
    "description": null,
    "objectField": "物料编码",
    "objectType": "material",
    "laneFields": "仓库编码",
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 1424,
    "title": "产成品",
    "isFinance": true,
    "bigClass": "资产类",
    "subClass": null,
    "description": null,
    "objectField": "物料编码",
    "objectType": "material",
    "laneFields": "仓库编码",
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 1471,
    "title": "存货跌价准备",
    "isFinance": true,
    "bigClass": "资产类",
    "subClass": null,
    "description": null,
    "objectField": "其他核算编码",
    "objectType": "otherObject",
    "laneFields": null,
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 1501,
    "title": "持有至到期投资",
    "isFinance": true,
    "bigClass": "资产类",
    "subClass": null,
    "description": null,
    "objectField": "其他核算编码",
    "objectType": "otherObject",
    "laneFields": null,
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 1503,
    "title": "可供出售金融资产",
    "isFinance": true,
    "bigClass": "资产类",
    "subClass": null,
    "description": null,
    "objectField": "其他核算编码",
    "objectType": "otherObject",
    "laneFields": null,
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 1505,
    "title": "持有待售资产",
    "isFinance": true,
    "bigClass": "资产类",
    "subClass": null,
    "description": null,
    "objectField": "其他核算编码",
    "objectType": "otherObject",
    "laneFields": null,
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 1511,
    "title": "长期股权投资",
    "isFinance": true,
    "bigClass": "资产类",
    "subClass": null,
    "description": null,
    "objectField": "往来编码",
    "objectType": "dealer",
    "laneFields": "往来标签",
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 1512,
    "title": "长期股权投资减值准备",
    "isFinance": true,
    "bigClass": "资产类",
    "subClass": null,
    "description": null,
    "objectField": "其他核算编码",
    "objectType": "otherObject",
    "laneFields": null,
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 1521,
    "title": "投资性房地产",
    "isFinance": true,
    "bigClass": "资产类",
    "subClass": null,
    "description": null,
    "objectField": "其他核算编码",
    "objectType": "otherObject",
    "laneFields": null,
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 1531,
    "title": "长期应收款",
    "isFinance": true,
    "bigClass": "资产类",
    "subClass": null,
    "description": null,
    "objectField": "其他核算编码",
    "objectType": "otherObject",
    "laneFields": null,
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 1601,
    "title": "固定资产",
    "isFinance": true,
    "bigClass": "资产类",
    "subClass": null,
    "description": null,
    "objectField": "设施编码",
    "objectType": "facility",
    "laneFields": "卡片,月份",
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 1602,
    "title": "累计折旧",
    "isFinance": true,
    "bigClass": "资产类",
    "subClass": null,
    "description": null,
    "objectField": "设施编码",
    "objectType": "facility",
    "laneFields": "卡片,月份",
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 1603,
    "title": "固定资产减值准备",
    "isFinance": true,
    "bigClass": "资产类",
    "subClass": null,
    "description": null,
    "objectField": "其他核算编码",
    "objectType": "otherObject",
    "laneFields": null,
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 1604,
    "title": "在建工程",
    "isFinance": true,
    "bigClass": "资产类",
    "subClass": null,
    "description": null,
    "objectField": "设施编码",
    "objectType": "facility",
    "laneFields": "",
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 1605,
    "title": "工程物资",
    "isFinance": true,
    "bigClass": "资产类",
    "subClass": null,
    "description": null,
    "objectField": "设施编码",
    "objectType": "facility",
    "laneFields": "",
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 1606,
    "title": "固定资产清理",
    "isFinance": true,
    "bigClass": "资产类",
    "subClass": null,
    "description": null,
    "objectField": "其他核算编码",
    "objectType": "otherObject",
    "laneFields": null,
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 1621,
    "title": "生产性生物资产",
    "isFinance": true,
    "bigClass": "资产类",
    "subClass": null,
    "description": null,
    "objectField": "设施编码",
    "objectType": "facility",
    "laneFields": null,
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 1631,
    "title": "油气资产",
    "isFinance": true,
    "bigClass": "资产类",
    "subClass": null,
    "description": null,
    "objectField": "设施编码",
    "objectType": "facility",
    "laneFields": null,
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 1701,
    "title": "无形资产",
    "isFinance": true,
    "bigClass": "资产类",
    "subClass": null,
    "description": null,
    "objectField": "设施编码",
    "objectType": "facility",
    "laneFields": null,
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 1702,
    "title": "累计摊销",
    "isFinance": true,
    "bigClass": "资产类",
    "subClass": null,
    "description": null,
    "objectField": "其他核算编码",
    "objectType": "otherObject",
    "laneFields": null,
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 1703,
    "title": "无形资产减值准备",
    "isFinance": true,
    "bigClass": "资产类",
    "subClass": null,
    "description": null,
    "objectField": "其他核算编码",
    "objectType": "otherObject",
    "laneFields": null,
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 1711,
    "title": "商誉",
    "isFinance": true,
    "bigClass": "资产类",
    "subClass": null,
    "description": null,
    "objectField": "其他核算编码",
    "objectType": "otherObject",
    "laneFields": null,
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 1712,
    "title": "商誉减值准备",
    "isFinance": true,
    "bigClass": "资产类",
    "subClass": null,
    "description": null,
    "objectField": "其他核算编码",
    "objectType": "otherObject",
    "laneFields": null,
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 1801,
    "title": "长期待摊费用",
    "isFinance": true,
    "bigClass": "资产类",
    "subClass": null,
    "description": null,
    "objectField": "其他核算编码",
    "objectType": "otherObject",
    "laneFields": null,
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 1802,
    "title": "长期待摊费用累计摊销",
    "isFinance": true,
    "bigClass": "资产类",
    "subClass": null,
    "description": null,
    "objectField": "其他核算编码",
    "objectType": "otherObject",
    "laneFields": null,
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 1811,
    "title": "递延所得税资产",
    "isFinance": true,
    "bigClass": "资产类",
    "subClass": null,
    "description": null,
    "objectField": "其他核算编码",
    "objectType": "otherObject",
    "laneFields": null,
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 1901,
    "title": "待处理财产损溢",
    "isFinance": true,
    "bigClass": "资产类",
    "subClass": null,
    "description": null,
    "objectField": "其他核算编码",
    "objectType": "otherObject",
    "laneFields": null,
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 1902,
    "title": "其他流动资产",
    "isFinance": true,
    "bigClass": "资产类",
    "subClass": null,
    "description": null,
    "objectField": "其他核算编码",
    "objectType": "otherObject",
    "laneFields": null,
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 1903,
    "title": "其他非流动资产",
    "isFinance": true,
    "bigClass": "资产类",
    "subClass": null,
    "description": null,
    "objectField": "其他核算编码",
    "objectType": "otherObject",
    "laneFields": null,
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 2001,
    "title": "短期借款",
    "isFinance": true,
    "bigClass": "负债类",
    "subClass": null,
    "description": null,
    "objectField": "往来编码",
    "objectType": "dealer",
    "laneFields": "往来标签",
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 2101,
    "title": "衍生金融负债",
    "isFinance": true,
    "bigClass": "负债类",
    "subClass": null,
    "description": null,
    "objectField": "其他核算编码",
    "objectType": "otherObject",
    "laneFields": null,
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 2102,
    "title": "以公允价值计量且其变动计入当期损益的金融负债",
    "isFinance": true,
    "bigClass": "负债类",
    "subClass": null,
    "description": null,
    "objectField": "其他核算编码",
    "objectType": "otherObject",
    "laneFields": null,
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 2191,
    "title": "预提费用",
    "isFinance": true,
    "bigClass": "负债类",
    "subClass": null,
    "description": null,
    "objectField": "其他核算编码",
    "objectType": "otherObject",
    "laneFields": null,
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 2201,
    "title": "应付票据",
    "isFinance": true,
    "bigClass": "负债类",
    "subClass": null,
    "description": null,
    "objectField": "往来编码",
    "objectType": "dealer",
    "laneFields": "往来标签",
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 2202,
    "title": "应付账款",
    "isFinance": true,
    "bigClass": "负债类",
    "subClass": null,
    "description": null,
    "objectField": "往来编码",
    "objectType": "dealer",
    "laneFields": "往来标签",
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 2203,
    "title": "预收账款",
    "isFinance": true,
    "bigClass": "负债类",
    "subClass": null,
    "description": null,
    "objectField": "往来编码",
    "objectType": "dealer",
    "laneFields": "往来标签",
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 2204,
    "title": "估价入库",
    "isFinance": true,
    "bigClass": "负债类",
    "subClass": null,
    "description": null,
    "objectField": "往来编码",
    "objectType": "dealer",
    "laneFields": "往来标签",
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 2211,
    "title": "应付职工薪酬",
    "isFinance": true,
    "bigClass": "负债类",
    "subClass": null,
    "description": null,
    "objectField": "往来编码",
    "objectType": "dealer",
    "laneFields": "往来标签",
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 2221,
    "title": "应交税费",
    "isFinance": true,
    "bigClass": "负债类",
    "subClass": null,
    "description": null,
    "objectField": "往来编码",
    "objectType": "dealer",
    "laneFields": "往来标签",
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 2231,
    "title": "应付利息",
    "isFinance": true,
    "bigClass": "负债类",
    "subClass": null,
    "description": null,
    "objectField": "往来编码",
    "objectType": "dealer",
    "laneFields": "往来标签",
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 2232,
    "title": "应付股利",
    "isFinance": true,
    "bigClass": "负债类",
    "subClass": null,
    "description": null,
    "objectField": "往来编码",
    "objectType": "dealer",
    "laneFields": "往来标签",
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 2241,
    "title": "其他应付款",
    "isFinance": true,
    "bigClass": "负债类",
    "subClass": null,
    "description": null,
    "objectField": "往来编码",
    "objectType": "dealer",
    "laneFields": "往来标签",
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 2401,
    "title": "递延收益",
    "isFinance": true,
    "bigClass": "负债类",
    "subClass": null,
    "description": null,
    "objectField": "其他核算编码",
    "objectType": "otherObject",
    "laneFields": null,
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 2501,
    "title": "长期借款",
    "isFinance": true,
    "bigClass": "负债类",
    "subClass": null,
    "description": null,
    "objectField": "往来编码",
    "objectType": "dealer",
    "laneFields": "往来标签",
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 2502,
    "title": "应付债券",
    "isFinance": true,
    "bigClass": "负债类",
    "subClass": null,
    "description": null,
    "objectField": "其他核算编码",
    "objectType": "otherObject",
    "laneFields": null,
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 2701,
    "title": "长期应付款",
    "isFinance": true,
    "bigClass": "负债类",
    "subClass": null,
    "description": null,
    "objectField": "其他核算编码",
    "objectType": "otherObject",
    "laneFields": null,
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 2702,
    "title": "未确认融资费用",
    "isFinance": true,
    "bigClass": "负债类",
    "subClass": null,
    "description": null,
    "objectField": "其他核算编码",
    "objectType": "otherObject",
    "laneFields": null,
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 2711,
    "title": "专项应付款",
    "isFinance": true,
    "bigClass": "负债类",
    "subClass": null,
    "description": null,
    "objectField": "其他核算编码",
    "objectType": "otherObject",
    "laneFields": null,
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 2801,
    "title": "预计负债",
    "isFinance": true,
    "bigClass": "负债类",
    "subClass": null,
    "description": null,
    "objectField": "其他核算编码",
    "objectType": "otherObject",
    "laneFields": null,
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 2901,
    "title": "递延所得税负债",
    "isFinance": true,
    "bigClass": "负债类",
    "subClass": null,
    "description": null,
    "objectField": "其他核算编码",
    "objectType": "otherObject",
    "laneFields": null,
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 2902,
    "title": "持有待售负债",
    "isFinance": true,
    "bigClass": "负债类",
    "subClass": null,
    "description": null,
    "objectField": "其他核算编码",
    "objectType": "otherObject",
    "laneFields": null,
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 2903,
    "title": "其他流动负债",
    "isFinance": true,
    "bigClass": "负债类",
    "subClass": null,
    "description": null,
    "objectField": "其他核算编码",
    "objectType": "otherObject",
    "laneFields": null,
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 2904,
    "title": "其他非流动负债",
    "isFinance": true,
    "bigClass": "负债类",
    "subClass": null,
    "description": null,
    "objectField": "其他核算编码",
    "objectType": "otherObject",
    "laneFields": null,
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 3101,
    "title": "衍生工具",
    "isFinance": true,
    "bigClass": "共同类",
    "subClass": null,
    "description": null,
    "objectField": "其他核算编码",
    "objectType": "otherObject",
    "laneFields": null,
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 3201,
    "title": "套期工具",
    "isFinance": true,
    "bigClass": "共同类",
    "subClass": null,
    "description": null,
    "objectField": "其他核算编码",
    "objectType": "otherObject",
    "laneFields": null,
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 3202,
    "title": "被套期项目",
    "isFinance": true,
    "bigClass": "共同类",
    "subClass": null,
    "description": null,
    "objectField": "其他核算编码",
    "objectType": "otherObject",
    "laneFields": null,
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 4001,
    "title": "实收资本",
    "isFinance": true,
    "bigClass": "所有者权益类",
    "subClass": null,
    "description": null,
    "objectField": "往来编码",
    "objectType": "dealer",
    "laneFields": "往来标签",
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 4002,
    "title": "资本公积",
    "isFinance": true,
    "bigClass": "所有者权益类",
    "subClass": null,
    "description": null,
    "objectField": "其他核算编码",
    "objectType": "otherObject",
    "laneFields": null,
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 4101,
    "title": "盈余公积",
    "isFinance": true,
    "bigClass": "所有者权益类",
    "subClass": null,
    "description": null,
    "objectField": "其他核算编码",
    "objectType": "otherObject",
    "laneFields": null,
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 4103,
    "title": "本年利润",
    "isFinance": true,
    "bigClass": "所有者权益类",
    "subClass": null,
    "description": null,
    "objectField": "其他核算编码",
    "objectType": "otherObject",
    "laneFields": null,
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 4104,
    "title": "未分配利润",
    "isFinance": true,
    "bigClass": "所有者权益类",
    "subClass": null,
    "description": null,
    "objectField": "其他核算编码",
    "objectType": "otherObject",
    "laneFields": null,
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 4201,
    "title": "库存股",
    "isFinance": true,
    "bigClass": "所有者权益类",
    "subClass": null,
    "description": null,
    "objectField": "其他核算编码",
    "objectType": "otherObject",
    "laneFields": null,
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 4301,
    "title": "其他权益工具",
    "isFinance": true,
    "bigClass": "所有者权益类",
    "subClass": null,
    "description": null,
    "objectField": "其他核算编码",
    "objectType": "otherObject",
    "laneFields": null,
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 4302,
    "title": "其他综合收益",
    "isFinance": true,
    "bigClass": "所有者权益类",
    "subClass": null,
    "description": null,
    "objectField": "其他核算编码",
    "objectType": "otherObject",
    "laneFields": null,
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 5001,
    "title": "生产成本",
    "isFinance": true,
    "bigClass": "成本类",
    "subClass": null,
    "description": null,
    "objectField": "其他核算编码",
    "objectType": "otherObject",
    "laneFields": null,
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 5101,
    "title": "制造费用",
    "isFinance": true,
    "bigClass": "成本类",
    "subClass": null,
    "description": null,
    "objectField": "费用编码",
    "objectType": "expenses",
    "laneFields": "部门,项目",
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 5201,
    "title": "劳务成本",
    "isFinance": true,
    "bigClass": "成本类",
    "subClass": null,
    "description": null,
    "objectField": "其他核算编码",
    "objectType": "otherObject",
    "laneFields": null,
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 5301,
    "title": "开发支出",
    "isFinance": true,
    "bigClass": "成本类",
    "subClass": null,
    "description": null,
    "objectField": "其他核算编码",
    "objectType": "otherObject",
    "laneFields": null,
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 5401,
    "title": "工程费用",
    "isFinance": true,
    "bigClass": "成本类",
    "subClass": null,
    "description": null,
    "objectField": "费用编码",
    "objectType": "expenses",
    "laneFields": "部门,项目",
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 5402,
    "title": "工程结算",
    "isFinance": true,
    "bigClass": "成本类",
    "subClass": null,
    "description": null,
    "objectField": "其他核算编码",
    "objectType": "otherObject",
    "laneFields": null,
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 6001,
    "title": "营业收入",
    "isFinance": true,
    "bigClass": "损益类",
    "subClass": null,
    "description": null,
    "objectField": "物料编码",
    "objectType": "material",
    "laneFields": "",
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 6051,
    "title": "其他业务收入",
    "isFinance": true,
    "bigClass": "损益类",
    "subClass": null,
    "description": null,
    "objectField": "其他核算编码",
    "objectType": "otherObject",
    "laneFields": null,
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 6111,
    "title": "投资收益",
    "isFinance": true,
    "bigClass": "损益类",
    "subClass": null,
    "description": null,
    "objectField": "其他核算编码",
    "objectType": "otherObject",
    "laneFields": null,
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 6112,
    "title": "资产处置收益",
    "isFinance": true,
    "bigClass": "损益类",
    "subClass": null,
    "description": null,
    "objectField": "其他核算编码",
    "objectType": "otherObject",
    "laneFields": null,
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 6113,
    "title": "其他收益",
    "isFinance": true,
    "bigClass": "损益类",
    "subClass": null,
    "description": null,
    "objectField": "其他核算编码",
    "objectType": "otherObject",
    "laneFields": null,
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 6301,
    "title": "营业外收入",
    "isFinance": true,
    "bigClass": "损益类",
    "subClass": null,
    "description": null,
    "objectField": "其他核算编码",
    "objectType": "otherObject",
    "laneFields": null,
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 6302,
    "title": "销售折扣与折让",
    "isFinance": true,
    "bigClass": "损益类",
    "subClass": null,
    "description": null,
    "objectField": "其他核算编码",
    "objectType": "otherObject",
    "laneFields": null,
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 6401,
    "title": "主营业务成本",
    "isFinance": true,
    "bigClass": "损益类",
    "subClass": null,
    "description": null,
    "objectField": "物料编码",
    "objectType": "material",
    "laneFields": "",
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 6402,
    "title": "其他业务成本",
    "isFinance": true,
    "bigClass": "损益类",
    "subClass": null,
    "description": null,
    "objectField": "其他核算编码",
    "objectType": "otherObject",
    "laneFields": null,
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 6403,
    "title": "税金及附加",
    "isFinance": true,
    "bigClass": "损益类",
    "subClass": null,
    "description": null,
    "objectField": "其他核算编码",
    "objectType": "otherObject",
    "laneFields": null,
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 6601,
    "title": "销售费用",
    "isFinance": true,
    "bigClass": "损益类",
    "subClass": null,
    "description": null,
    "objectField": "费用编码",
    "objectType": "expenses",
    "laneFields": "部门,项目",
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 6602,
    "title": "管理费用",
    "isFinance": true,
    "bigClass": "损益类",
    "subClass": null,
    "description": null,
    "objectField": "费用编码",
    "objectType": "expenses",
    "laneFields": "部门,项目",
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 6603,
    "title": "财务费用",
    "isFinance": true,
    "bigClass": "损益类",
    "subClass": null,
    "description": null,
    "objectField": "费用编码",
    "objectType": "expenses",
    "laneFields": "部门,项目",
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 6604,
    "title": "研发费用",
    "isFinance": true,
    "bigClass": "损益类",
    "subClass": null,
    "description": null,
    "objectField": "费用编码",
    "objectType": "expenses",
    "laneFields": "部门,项目",
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 6701,
    "title": "资产减值损失",
    "isFinance": true,
    "bigClass": "损益类",
    "subClass": null,
    "description": null,
    "objectField": "其他核算编码",
    "objectType": "otherObject",
    "laneFields": null,
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 6711,
    "title": "营业外支出",
    "isFinance": true,
    "bigClass": "损益类",
    "subClass": null,
    "description": null,
    "objectField": "其他核算编码",
    "objectType": "otherObject",
    "laneFields": null,
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 6801,
    "title": "所得税费用",
    "isFinance": true,
    "bigClass": "损益类",
    "subClass": null,
    "description": null,
    "objectField": "其他核算编码",
    "objectType": "otherObject",
    "laneFields": null,
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 6901,
    "title": "以前年度损益调整",
    "isFinance": true,
    "bigClass": "损益类",
    "subClass": null,
    "description": null,
    "objectField": "其他核算编码",
    "objectType": "otherObject",
    "laneFields": null,
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 91101,
    "title": "待收票",
    "isFinance": false,
    "bigClass": null,
    "subClass": null,
    "description": null,
    "objectField": "物料编码",
    "objectType": "material",
    "laneFields": "往来编码,往来标签",
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 91102,
    "title": "待收票-设施",
    "isFinance": false,
    "bigClass": null,
    "subClass": null,
    "description": null,
    "objectField": "设施编码",
    "objectType": "facility",
    "laneFields": "往来编码,项目",
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 91104,
    "title": "已收可退票",
    "isFinance": false,
    "bigClass": null,
    "subClass": null,
    "description": null,
    "objectField": "物料编码",
    "objectType": "material",
    "laneFields": "往来编码,往来标签",
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 91421,
    "title": "批次存货",
    "isFinance": false,
    "bigClass": null,
    "subClass": null,
    "description": null,
    "objectField": "物料编码",
    "objectType": "material",
    "laneFields": "仓库编码,生产日期,生产批号,项目",
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 91605,
    "title": "待验收采购订单",
    "isFinance": false,
    "bigClass": null,
    "subClass": null,
    "description": null,
    "objectField": "设施编码",
    "objectType": "facility",
    "laneFields": "往来编码,采购订单号,项目,往来标签",
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 91606,
    "title": "待下单的采购",
    "isFinance": false,
    "bigClass": null,
    "subClass": null,
    "description": null,
    "objectField": "设施编码",
    "objectType": "facility",
    "laneFields": "采购申请,项目",
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 92201,
    "title": "待开票",
    "isFinance": false,
    "bigClass": null,
    "subClass": null,
    "description": null,
    "objectField": "物料编码",
    "objectType": "material",
    "laneFields": "往来编码,销售订单号,项目,往来标签",
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 92301,
    "title": "待付预付款",
    "isFinance": false,
    "bigClass": null,
    "subClass": null,
    "description": null,
    "objectField": "往来编码",
    "objectType": "dealer",
    "laneFields": "采购订单,项目,往来标签",
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 92401,
    "title": "待收预收款",
    "isFinance": false,
    "bigClass": null,
    "subClass": null,
    "description": null,
    "objectField": "往来编码",
    "objectType": "dealer",
    "laneFields": "销售订单号,项目,往来标签",
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 97051,
    "title": "工单待派工",
    "isFinance": false,
    "bigClass": null,
    "subClass": null,
    "description": null,
    "objectField": "物料编码",
    "objectType": "material",
    "laneFields": "工序编码,加工订单号,项目",
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 97502,
    "title": "待下单的采购",
    "isFinance": false,
    "bigClass": null,
    "subClass": null,
    "description": null,
    "objectField": "物料编码",
    "objectType": "material",
    "laneFields": "项目,采购申请",
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 98001,
    "title": "待领料的加工单",
    "isFinance": false,
    "bigClass": null,
    "subClass": null,
    "description": null,
    "objectField": "物料编码",
    "objectType": "material",
    "laneFields": "工序编码,开工日期,工作中心,项目",
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 98003,
    "title": "委外加工待领料",
    "isFinance": false,
    "bigClass": null,
    "subClass": null,
    "description": null,
    "objectField": "物料编码",
    "objectType": "material",
    "laneFields": "加工订单号,项目",
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 98051,
    "title": "工单可验收",
    "isFinance": false,
    "bigClass": null,
    "subClass": null,
    "description": null,
    "objectField": "物料编码",
    "objectType": "material",
    "laneFields": "派工单号,项目",
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 98101,
    "title": "工单待配料",
    "isFinance": false,
    "bigClass": null,
    "subClass": null,
    "description": null,
    "objectField": "物料编码",
    "objectType": "material",
    "laneFields": "工序编码,派工单号,项目",
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 98501,
    "title": "待验收加工订单",
    "isFinance": false,
    "bigClass": null,
    "subClass": null,
    "description": null,
    "objectField": "物料编码",
    "objectType": "material",
    "laneFields": "加工订单号,项目",
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 98502,
    "title": "待验收采购订单",
    "isFinance": false,
    "bigClass": null,
    "subClass": null,
    "description": null,
    "objectField": "物料编码",
    "objectType": "material",
    "laneFields": "采购订单号,往来编码,项目,往来标签",
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 98505,
    "title": "服务采购待验收",
    "isFinance": false,
    "bigClass": null,
    "subClass": null,
    "description": null,
    "objectField": "物料编码",
    "objectType": "material",
    "laneFields": "往来编码,采购订单号,项目,往来标签",
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 98506,
    "title": "委外加工待验收",
    "isFinance": false,
    "bigClass": null,
    "subClass": null,
    "description": null,
    "objectField": "物料编码",
    "objectType": "material",
    "laneFields": "往来编码,加工订单号,项目,往来标签",
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 98507,
    "title": "待验收采购订单",
    "isFinance": false,
    "bigClass": null,
    "subClass": null,
    "description": null,
    "objectField": "物料编码",
    "objectType": "material",
    "laneFields": "往来编码,采购订单号,项目,往来标签",
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 98801,
    "title": "待交付的订单",
    "isFinance": false,
    "bigClass": null,
    "subClass": null,
    "description": null,
    "objectField": "物料编码",
    "objectType": "material",
    "laneFields": "往来编码,销售订单号,项目,往来标签",
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 98810,
    "title": "待上架",
    "isFinance": false,
    "bigClass": null,
    "subClass": null,
    "description": null,
    "objectField": "物料编码",
    "objectType": "material",
    "laneFields": "仓库编码",
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 98812,
    "title": "箱码存货",
    "isFinance": false,
    "bigClass": null,
    "subClass": null,
    "description": null,
    "objectField": "物料编码",
    "objectType": "material",
    "laneFields": "仓库编码,库位编码,箱码",
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 98815,
    "title": "待拣货",
    "isFinance": false,
    "bigClass": null,
    "subClass": null,
    "description": null,
    "objectField": "物料编码",
    "objectType": "material",
    "laneFields": "仓库编码",
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 98817,
    "title": "受托存货入库",
    "isFinance": false,
    "bigClass": null,
    "subClass": null,
    "description": null,
    "objectField": "物料编码",
    "objectType": "material",
    "laneFields": "仓库编码,往来编码",
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 999903,
    "title": "待质检",
    "isFinance": false,
    "bigClass": null,
    "subClass": null,
    "description": null,
    "objectField": "物料编码",
    "objectType": "material",
    "laneFields": "往来编码,项目,往来标签",
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 999907,
    "title": "换货待入库",
    "isFinance": false,
    "bigClass": null,
    "subClass": null,
    "description": null,
    "objectField": "物料编码",
    "objectType": "material",
    "laneFields": "往来编码,采购订单号,项目,往来标签",
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 999908,
    "title": "设备换货待入库",
    "isFinance": false,
    "bigClass": null,
    "subClass": null,
    "description": null,
    "objectField": "设施编码",
    "objectType": "facility",
    "laneFields": "往来编码,采购订单号,项目,往来标签",
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  },
  {
    "id": 999909,
    "title": "加工待质检",
    "isFinance": false,
    "bigClass": null,
    "subClass": null,
    "description": null,
    "objectField": "物料编码",
    "objectType": "material",
    "laneFields": "加工订单号,项目",
    "objectBusinessType": null,
    "allowNegative": null,
    "costCalcConfig": null
  }
] as const;
