export {
  EOG_3D_PACKAGE_ID as EOG_3D_VIEWER_PACKAGE_ID,
  EOG_3D_VIEWER_FEATURE_ID,
  EOG_3D_VIEWER_CAPABILITY,
  EOG_3D_VIEWER_EXPERIENCE_ID,
  EOG_3D_VIEWER_PAGE_ID,
  EOG_3D_VIEWER_PAGE_SOURCE,
  EOG_3D_VIEWER_ROUTE,
  eog3dPackage as eog3dViewerPackage
} from "../eog-3d/package.js";
