import type { PackageManifestV010 } from "../../contracts/package.js";

export const ENTERPRISE_AGENT_PACKAGE_ID = "enterprise-agent";
export const ENTERPRISE_AGENT_FEATURE_ID = "enterprise-agent.default";
export const ENTERPRISE_AGENT_PAGE_SOURCE = "app://enterprise-agent/pages/home";
export const ENTERPRISE_AGENT_MOBILE_PAGE_SOURCE = "app://enterprise-agent/pages/mobile-home";
export const ENTERPRISE_AGENT_SETUP_PAGE_SOURCE = "app://enterprise-agent/pages/setup";
export const ENTERPRISE_AGENT_MEMORY_REVIEW_PAGE_SOURCE = "app://enterprise-agent/pages/memory-review";
export const ENTERPRISE_AGENT_QUALITY_PAGE_SOURCE = "app://enterprise-agent/pages/quality";
export const ENTERPRISE_AGENT_QUALITY_REVIEW_PAGE_SOURCE = "app://enterprise-agent/pages/quality-review";
export const ENTERPRISE_AGENT_FOLLOW_UP_PAGE_SOURCE = "app://enterprise-agent/pages/follow-ups";
export const ENTERPRISE_AGENT_MOBILE_FOLLOW_UP_PAGE_SOURCE = "app://enterprise-agent/pages/mobile-follow-ups";

const enMessages = {
  "workbench.activity.label": "Personal Agent",
  "review.personal-agent.memory-review.title": "Memory review",
  "review.personal-agent.memory-review.description": "Decide which proposed knowledge should become durable Memory. Review signals are suggestions only; you remain in control of every decision.",
  "review.personal-agent.memory-review.empty": "No Memory proposals need review.",
  "review.personal-agent.memory-review.status.pending.label": "Pending",
  "review.personal-agent.memory-review.status.attention.label": "Needs attention",
  "review.personal-agent.memory-review.status.accepted.label": "Accepted",
  "review.personal-agent.memory-review.status.rejected.label": "Rejected",
  "review.personal-agent.memory-review.metric.confidence.label": "Confidence",
  "review.personal-agent.memory-review.metric.evidence.label": "Evidence",
  "review.personal-agent.memory-review.metric.source-trust-host-verified.label": "Host-verified sources",
  "review.personal-agent.memory-review.metric.source-trust-declared.label": "Declared sources",
  "review.personal-agent.memory-review.metric.source-trust-unverified.label": "Unverified sources",
  "review.personal-agent.memory-review.metric.conflicts.label": "Review signals",
  "review.personal-agent.memory-review.metric.context.label": "Context",
  "review.personal-agent.memory-review.field.kind.label": "Kind",
  "review.personal-agent.memory-review.field.kind.option.FACT.label": "Fact",
  "review.personal-agent.memory-review.field.kind.option.CLAIM.label": "Claim",
  "review.personal-agent.memory-review.field.kind.option.EXPERIENCE.label": "Experience",
  "review.personal-agent.memory-review.field.kind.option.PRACTICE.label": "Practice",
  "review.personal-agent.memory-review.field.summary.label": "Summary",
  "review.personal-agent.memory-review.action.save.label": "Save edit",
  "review.personal-agent.memory-review.action.accept.label": "Accept",
  "review.personal-agent.memory-review.action.reject.label": "Reject",
  "navigation.enterprise-agent.nav.label": "Personal Agent",
  "page.enterprise-agent.home.title": "Personal Agent",
  "page.enterprise-agent.setup.title": "Personal Agent setup",
  "chat.enterprise-agent.home.composer.placeholder": "Ask or describe a task",
  "chat.enterprise-agent.home.composer.sendLabel": "Send",
  "chat.enterprise-agent.home.context.label": "Current context",
  "chat.enterprise-agent.home.context.selector.ariaLabel": "Choose context",
  "chat.enterprise-agent.home.context.option.personal.label": "Personal",
  "chat.enterprise-agent.home.readiness.ready.label": "Ready",
  "chat.enterprise-agent.home.readiness.ready.message": "Personal Agent is ready.",
  "chat.enterprise-agent.home.readiness.setup-required.label": "Needs setup",
  "chat.enterprise-agent.home.readiness.setup-required.message": "Connect an AI service before using Personal Agent.",
  "chat.enterprise-agent.home.readiness.degraded.label": "Degraded",
  "chat.enterprise-agent.home.readiness.degraded.message": "The connected AI service needs attention.",
  "chat.enterprise-agent.home.readiness.unavailable.label": "Unavailable",
  "chat.enterprise-agent.home.readiness.unavailable.message": "The connected AI service is unavailable.",
  "chat.enterprise-agent.home.action.open-setup.label": "Open setup",
  "chat.enterprise-agent.home.empty.title": "How can I help?",
  "chat.enterprise-agent.home.empty.description": "I can inspect your available apps and Context, explain what is happening, and prepare an opinion or plan.",
  "chat.enterprise-agent.home.suggestion.attention.label": "What needs my attention?",
  "chat.enterprise-agent.home.suggestion.context.label": "Explain my current context",
  "setup.personal-agent.setup.title": "Set up Personal Agent",
  "setup.personal-agent.setup.description": "Follow these steps to connect an AI service. Only the choices needed to get started are shown here.",
  "setup.personal-agent.setup.step.provider.title": "Choose an AI service",
  "setup.personal-agent.setup.step.provider.description": "Select the service Personal Agent will use. If you do not have one installed yet, browse the available AI services.",
  "setup.personal-agent.setup.step.provider.status.current": "Choose now",
  "setup.personal-agent.setup.step.provider.status.complete": "Complete",
  "setup.personal-agent.setup.step.provider.status.pending": "Waiting",
  "setup.personal-agent.setup.step.credentials.title": "Connect the service",
  "setup.personal-agent.setup.step.credentials.description": "Enter the credentials and model settings required by the selected service.",
  "setup.personal-agent.setup.step.credentials.status.current": "Connect now",
  "setup.personal-agent.setup.step.credentials.status.complete": "Complete",
  "setup.personal-agent.setup.step.credentials.status.pending": "Waiting",
  "setup.personal-agent.setup.step.credentials.status.blocked": "Waiting",
  "setup.personal-agent.setup.step.readiness.title": "Check the connection",
  "setup.personal-agent.setup.step.readiness.description": "We’ll verify that Personal Agent can reach the selected service and use it.",
  "setup.personal-agent.setup.step.readiness.status.current": "Check now",
  "setup.personal-agent.setup.step.readiness.status.complete": "Complete",
  "setup.personal-agent.setup.step.readiness.status.blocked": "Waiting",
  "setup.personal-agent.setup.step.readiness.status.error": "Needs attention",
  "setup.personal-agent.setup.step.ready.title": "Ready to use",
  "setup.personal-agent.setup.step.ready.description": "Setup is complete. You can start using Personal Agent now.",
  "setup.personal-agent.setup.step.ready.status.complete": "Complete",
  "setup.personal-agent.setup.step.ready.status.blocked": "Waiting",
  "setup.personal-agent.setup.action.choose-provider.label": "Choose AI service",
  "setup.personal-agent.setup.action.open-provider-catalog.label": "Browse AI services",
  "setup.personal-agent.setup.action.configure-provider.label": "Connect service",
  "setup.personal-agent.setup.action.open-agent.label": "Start using Personal Agent",
  "setup.personal-agent.setup.action.provider-status.label": "Connection details",
  "setup.personal-agent.setup.action.check-provider-status.label": "Check connection",
  "setup.personal-agent.setup.action.recheck-setup.label": "Try again",
  "setup.personal-agent.setup.action.review-memory.label": "Review Memory",
  "setup.personal-agent.setup.action.memory-governance.label": "Memory Governance",
  "setup.personal-agent.setup.action.memory-source-health.label": "Memory Source Health",
  "setup.personal-agent.setup.action.agent-quality.label": "Personal Agent Quality",
  "setup.personal-agent.setup.action.agent-follow-ups.label": "Personal Agent Follow-ups",
  "review.personal-agent.memory-review.technicalDetails.label": "Technical details",
  "review.personal-agent.memory-review.technicalDetail.proposalId.label": "Proposal ID",
  "review.personal-agent.memory-review.technicalDetail.contextId.label": "Context ID",
  "review.personal-agent.memory-review.technicalDetail.revisionId.label": "Revision ID",
  "review.personal-agent.memory-review.technicalDetail.evidenceQuality.label": "Evidence quality",
  "review.personal-agent.memory-review.technicalDetail.evidenceReference.label": "Evidence reference",
  "review.personal-agent.memory-review.technicalDetail.sourceId.label": "Source ID",
  "review.personal-agent.memory-review.technicalDetail.sourceType.label": "Source type",
  "review.personal-agent.memory-review.technicalDetail.sourceTrust.label": "Source trust",
  "review.personal-agent.memory-review.technicalDetail.trustPolicyId.label": "Trust policy ID",
  "review.personal-agent.memory-review.technicalDetail.reviewSignal.label": "Review signal",
  "review.personal-agent.memory-review.technicalDetail.relatedMemoryId.label": "Related Memory ID",
  "review.personal-agent.memory-review.technicalDetail.signalExplanation.label": "Signal explanation",
  "review.personal-agent.memory-review.technicalDetail.duplicateMemoryId.label": "Duplicate Memory ID",
  "review.personal-agent.memory-review.technicalDetail.canonicalMemoryId.label": "Canonical Memory ID",
  "review.personal-agent.memory-review.field.reason.label": "Why this was suggested",
  "review.personal-agent.memory-review.evidence.reference.title": "Evidence",
  "review.personal-agent.memory-review.evidence.reference.source": "Referenced evidence",
  "review.personal-agent.memory-review.evidence.reference-unverified.title": "Evidence",
  "review.personal-agent.memory-review.evidence.reference-unverified.source": "Unverified evidence",
  "review.personal-agent.memory-review.evidence.source-host-verified.source": "Verified source",
  "review.personal-agent.memory-review.evidence.source-declared.source": "Declared source",
  "review.personal-agent.memory-review.evidence.source-unverified.source": "Unverified source",
  "review.personal-agent.memory-review.evidence.source-host-verified-generic.title": "Evidence source",
  "review.personal-agent.memory-review.evidence.source-host-verified-generic.source": "Verified source",
  "review.personal-agent.memory-review.evidence.source-declared-generic.title": "Evidence source",
  "review.personal-agent.memory-review.evidence.source-declared-generic.source": "Declared source",
  "review.personal-agent.memory-review.evidence.source-unverified-generic.title": "Evidence source",
  "review.personal-agent.memory-review.evidence.source-unverified-generic.source": "Unverified source",
  "review.personal-agent.memory-review.evidence.signal-potential-duplicate.title": "Possible duplicate",
  "review.personal-agent.memory-review.evidence.signal-potential-duplicate.source": "Review signal",
  "review.personal-agent.memory-review.evidence.signal-potential-contradiction.title": "Possible contradiction",
  "review.personal-agent.memory-review.evidence.signal-potential-contradiction.source": "Review signal",
  "review.personal-agent.memory-review.evidence.signal-supersession-candidate.title": "May replace existing Memory",
  "review.personal-agent.memory-review.evidence.signal-supersession-candidate.source": "Review signal",
  "review.personal-agent.memory-review.item.canonicalization.title": "Review possible duplicate",
  "review.personal-agent.memory-review.item.canonicalization.summary": "If accepted, the duplicate will be hidden from normal retrieval while the existing Memory remains available. No Memory text is deleted.",
  "review.personal-agent.memory-review.evidence.canonicalization-duplicate.source": "Duplicate to hide",
  "review.personal-agent.memory-review.evidence.canonicalization-canonical.source": "Memory to keep",
  "review.personal-agent.memory-review.action.accept-canonicalization.label": "Confirm duplicate",
  "review.personal-agent.memory-review.action.reject-canonicalization.label": "Keep both",
};

const zhCnMessages = {
  "workbench.activity.label": "个人代理",
  "review.personal-agent.memory-review.title": "记忆审核",
  "review.personal-agent.memory-review.description": "决定哪些候选知识值得成为长期记忆。审核提示只是建议，每一次接受或拒绝都由你决定。",
  "review.personal-agent.memory-review.empty": "当前没有需要审核的记忆提案。",
  "review.personal-agent.memory-review.status.pending.label": "待审核",
  "review.personal-agent.memory-review.status.attention.label": "需要关注",
  "review.personal-agent.memory-review.status.accepted.label": "已接受",
  "review.personal-agent.memory-review.status.rejected.label": "已拒绝",
  "review.personal-agent.memory-review.metric.confidence.label": "置信度",
  "review.personal-agent.memory-review.metric.evidence.label": "证据",
  "review.personal-agent.memory-review.metric.source-trust-host-verified.label": "Host 已验证来源",
  "review.personal-agent.memory-review.metric.source-trust-declared.label": "已声明来源",
  "review.personal-agent.memory-review.metric.source-trust-unverified.label": "未验证来源",
  "review.personal-agent.memory-review.metric.conflicts.label": "审核信号",
  "review.personal-agent.memory-review.metric.context.label": "上下文",
  "review.personal-agent.memory-review.field.kind.label": "类型",
  "review.personal-agent.memory-review.field.kind.option.FACT.label": "事实",
  "review.personal-agent.memory-review.field.kind.option.CLAIM.label": "主张",
  "review.personal-agent.memory-review.field.kind.option.EXPERIENCE.label": "经验",
  "review.personal-agent.memory-review.field.kind.option.PRACTICE.label": "实践",
  "review.personal-agent.memory-review.field.summary.label": "摘要",
  "review.personal-agent.memory-review.action.save.label": "保存编辑",
  "review.personal-agent.memory-review.action.accept.label": "接受",
  "review.personal-agent.memory-review.action.reject.label": "拒绝",
  "navigation.enterprise-agent.nav.label": "个人代理",
  "page.enterprise-agent.home.title": "个人代理",
  "page.enterprise-agent.setup.title": "个人代理设置",
  "chat.enterprise-agent.home.composer.placeholder": "询问问题或描述任务",
  "chat.enterprise-agent.home.composer.sendLabel": "发送",
  "chat.enterprise-agent.home.context.label": "当前上下文",
  "chat.enterprise-agent.home.context.selector.ariaLabel": "选择上下文",
  "chat.enterprise-agent.home.context.option.personal.label": "个人",
  "chat.enterprise-agent.home.readiness.ready.label": "就绪",
  "chat.enterprise-agent.home.readiness.ready.message": "个人代理已就绪。",
  "chat.enterprise-agent.home.readiness.setup-required.label": "需要设置",
  "chat.enterprise-agent.home.readiness.setup-required.message": "使用个人代理前，请先连接 AI 服务。",
  "chat.enterprise-agent.home.readiness.degraded.label": "性能下降",
  "chat.enterprise-agent.home.readiness.degraded.message": "已连接的 AI 服务需要处理。",
  "chat.enterprise-agent.home.readiness.unavailable.label": "不可用",
  "chat.enterprise-agent.home.readiness.unavailable.message": "已连接的 AI 服务当前不可用。",
  "chat.enterprise-agent.home.action.open-setup.label": "打开设置",
  "chat.enterprise-agent.home.empty.title": "我可以帮你做什么？",
  "chat.enterprise-agent.home.empty.description": "我可以查看可用应用和上下文，解释当前情况，并准备意见或方案。",
  "chat.enterprise-agent.home.suggestion.attention.label": "现在有哪些事情需要我关注？",
  "chat.enterprise-agent.home.suggestion.context.label": "解释我当前的上下文",
  "setup.personal-agent.setup.title": "设置个人代理",
  "setup.personal-agent.setup.description": "按照以下步骤连接 AI 服务。这里仅显示开始使用所需的必要选项。",
  "setup.personal-agent.setup.step.provider.title": "选择 AI 服务",
  "setup.personal-agent.setup.step.provider.description": "选择个人代理要使用的服务。如果尚未安装，可浏览可用的 AI 服务。",
  "setup.personal-agent.setup.step.provider.status.current": "现在选择",
  "setup.personal-agent.setup.step.provider.status.complete": "完成",
  "setup.personal-agent.setup.step.provider.status.pending": "等待",
  "setup.personal-agent.setup.step.credentials.title": "连接服务",
  "setup.personal-agent.setup.step.credentials.description": "填写所选服务要求的凭据和模型设置。",
  "setup.personal-agent.setup.step.credentials.status.current": "现在连接",
  "setup.personal-agent.setup.step.credentials.status.complete": "完成",
  "setup.personal-agent.setup.step.credentials.status.pending": "等待",
  "setup.personal-agent.setup.step.credentials.status.blocked": "等待",
  "setup.personal-agent.setup.step.readiness.title": "检查连接",
  "setup.personal-agent.setup.step.readiness.description": "系统会确认个人代理能够连接并使用所选服务。",
  "setup.personal-agent.setup.step.readiness.status.current": "现在检查",
  "setup.personal-agent.setup.step.readiness.status.complete": "完成",
  "setup.personal-agent.setup.step.readiness.status.blocked": "等待",
  "setup.personal-agent.setup.step.readiness.status.error": "需要处理",
  "setup.personal-agent.setup.step.ready.title": "可以使用了",
  "setup.personal-agent.setup.step.ready.description": "设置已完成，现在可以开始使用个人代理。",
  "setup.personal-agent.setup.step.ready.status.complete": "完成",
  "setup.personal-agent.setup.step.ready.status.blocked": "等待",
  "setup.personal-agent.setup.action.choose-provider.label": "选择 AI 服务",
  "setup.personal-agent.setup.action.open-provider-catalog.label": "浏览 AI 服务",
  "setup.personal-agent.setup.action.configure-provider.label": "连接服务",
  "setup.personal-agent.setup.action.open-agent.label": "开始使用个人代理",
  "setup.personal-agent.setup.action.provider-status.label": "连接详情",
  "setup.personal-agent.setup.action.check-provider-status.label": "检查连接",
  "setup.personal-agent.setup.action.recheck-setup.label": "再试一次",
  "setup.personal-agent.setup.action.review-memory.label": "审核记忆",
  "setup.personal-agent.setup.action.memory-governance.label": "记忆治理",
  "setup.personal-agent.setup.action.memory-source-health.label": "记忆来源健康状态",
  "setup.personal-agent.setup.action.agent-quality.label": "个人代理质量",
  "setup.personal-agent.setup.action.agent-follow-ups.label": "个人代理后续事项",
  "review.personal-agent.memory-review.technicalDetails.label": "技术详情",
  "review.personal-agent.memory-review.technicalDetail.proposalId.label": "提案 ID",
  "review.personal-agent.memory-review.technicalDetail.contextId.label": "上下文 ID",
  "review.personal-agent.memory-review.technicalDetail.revisionId.label": "修订 ID",
  "review.personal-agent.memory-review.technicalDetail.evidenceQuality.label": "证据质量",
  "review.personal-agent.memory-review.technicalDetail.evidenceReference.label": "证据引用",
  "review.personal-agent.memory-review.technicalDetail.sourceId.label": "来源 ID",
  "review.personal-agent.memory-review.technicalDetail.sourceType.label": "来源类型",
  "review.personal-agent.memory-review.technicalDetail.sourceTrust.label": "来源可信级别",
  "review.personal-agent.memory-review.technicalDetail.trustPolicyId.label": "信任策略 ID",
  "review.personal-agent.memory-review.technicalDetail.reviewSignal.label": "审核信号",
  "review.personal-agent.memory-review.technicalDetail.relatedMemoryId.label": "相关记忆 ID",
  "review.personal-agent.memory-review.technicalDetail.signalExplanation.label": "信号说明",
  "review.personal-agent.memory-review.technicalDetail.duplicateMemoryId.label": "重复记忆 ID",
  "review.personal-agent.memory-review.technicalDetail.canonicalMemoryId.label": "保留记忆 ID",
  "review.personal-agent.memory-review.field.reason.label": "建议原因",
  "review.personal-agent.memory-review.evidence.reference.title": "证据",
  "review.personal-agent.memory-review.evidence.reference.source": "已引用证据",
  "review.personal-agent.memory-review.evidence.reference-unverified.title": "证据",
  "review.personal-agent.memory-review.evidence.reference-unverified.source": "未验证证据",
  "review.personal-agent.memory-review.evidence.source-host-verified.source": "已验证来源",
  "review.personal-agent.memory-review.evidence.source-declared.source": "已声明来源",
  "review.personal-agent.memory-review.evidence.source-unverified.source": "未验证来源",
  "review.personal-agent.memory-review.evidence.source-host-verified-generic.title": "证据来源",
  "review.personal-agent.memory-review.evidence.source-host-verified-generic.source": "已验证来源",
  "review.personal-agent.memory-review.evidence.source-declared-generic.title": "证据来源",
  "review.personal-agent.memory-review.evidence.source-declared-generic.source": "已声明来源",
  "review.personal-agent.memory-review.evidence.source-unverified-generic.title": "证据来源",
  "review.personal-agent.memory-review.evidence.source-unverified-generic.source": "未验证来源",
  "review.personal-agent.memory-review.evidence.signal-potential-duplicate.title": "可能重复",
  "review.personal-agent.memory-review.evidence.signal-potential-duplicate.source": "审核提示",
  "review.personal-agent.memory-review.evidence.signal-potential-contradiction.title": "可能矛盾",
  "review.personal-agent.memory-review.evidence.signal-potential-contradiction.source": "审核提示",
  "review.personal-agent.memory-review.evidence.signal-supersession-candidate.title": "可能替代已有记忆",
  "review.personal-agent.memory-review.evidence.signal-supersession-candidate.source": "审核提示",
  "review.personal-agent.memory-review.item.canonicalization.title": "审核可能重复的记忆",
  "review.personal-agent.memory-review.item.canonicalization.summary": "接受后，重复项会从普通检索中隐藏，现有记忆继续保留。不会删除任何记忆正文。",
  "review.personal-agent.memory-review.evidence.canonicalization-duplicate.source": "将隐藏的重复项",
  "review.personal-agent.memory-review.evidence.canonicalization-canonical.source": "继续保留的记忆",
  "review.personal-agent.memory-review.action.accept-canonicalization.label": "确认重复",
  "review.personal-agent.memory-review.action.reject-canonicalization.label": "两项都保留",
};

const jaMessages = {
  "workbench.activity.label": "パーソナルエージェント",
  "review.personal-agent.memory-review.title": "メモリーレビュー",
  "review.personal-agent.memory-review.description": "どの候補知識を長期メモリーとして残すかを判断します。レビューシグナルは提案にすぎず、承認・却下は常にあなたが決めます。",
  "review.personal-agent.memory-review.empty": "レビューが必要なメモリー提案はありません。",
  "review.personal-agent.memory-review.status.pending.label": "レビュー待ち",
  "review.personal-agent.memory-review.status.attention.label": "要確認",
  "review.personal-agent.memory-review.status.accepted.label": "承認済み",
  "review.personal-agent.memory-review.status.rejected.label": "却下済み",
  "review.personal-agent.memory-review.metric.confidence.label": "信頼度",
  "review.personal-agent.memory-review.metric.evidence.label": "証拠",
  "review.personal-agent.memory-review.metric.source-trust-host-verified.label": "Host 検証済みソース",
  "review.personal-agent.memory-review.metric.source-trust-declared.label": "申告済みソース",
  "review.personal-agent.memory-review.metric.source-trust-unverified.label": "未検証ソース",
  "review.personal-agent.memory-review.metric.conflicts.label": "レビュー信号",
  "review.personal-agent.memory-review.metric.context.label": "コンテキスト",
  "review.personal-agent.memory-review.field.kind.label": "種類",
  "review.personal-agent.memory-review.field.kind.option.FACT.label": "事実",
  "review.personal-agent.memory-review.field.kind.option.CLAIM.label": "主張",
  "review.personal-agent.memory-review.field.kind.option.EXPERIENCE.label": "経験",
  "review.personal-agent.memory-review.field.kind.option.PRACTICE.label": "プラクティス",
  "review.personal-agent.memory-review.field.summary.label": "要約",
  "review.personal-agent.memory-review.action.save.label": "編集を保存",
  "review.personal-agent.memory-review.action.accept.label": "承認",
  "review.personal-agent.memory-review.action.reject.label": "却下",
  "navigation.enterprise-agent.nav.label": "パーソナルエージェント",
  "page.enterprise-agent.home.title": "パーソナルエージェント",
  "page.enterprise-agent.setup.title": "パーソナルエージェントのセットアップ",
  "chat.enterprise-agent.home.composer.placeholder": "質問またはタスクを入力してください",
  "chat.enterprise-agent.home.composer.sendLabel": "送信",
  "chat.enterprise-agent.home.context.label": "現在のコンテキスト",
  "chat.enterprise-agent.home.context.selector.ariaLabel": "コンテキストを選択",
  "chat.enterprise-agent.home.context.option.personal.label": "個人",
  "chat.enterprise-agent.home.readiness.ready.label": "準備完了",
  "chat.enterprise-agent.home.readiness.ready.message": "パーソナルエージェントを利用できます。",
  "chat.enterprise-agent.home.readiness.setup-required.label": "セットアップが必要",
  "chat.enterprise-agent.home.readiness.setup-required.message": "パーソナルエージェントを使う前に AI サービスを接続してください。",
  "chat.enterprise-agent.home.readiness.degraded.label": "低下",
  "chat.enterprise-agent.home.readiness.degraded.message": "接続中の AI サービスに対応が必要です。",
  "chat.enterprise-agent.home.readiness.unavailable.label": "利用不可",
  "chat.enterprise-agent.home.readiness.unavailable.message": "接続中の AI サービスは現在利用できません。",
  "chat.enterprise-agent.home.action.open-setup.label": "セットアップを開く",
  "chat.enterprise-agent.home.empty.title": "何をお手伝いしましょうか？",
  "chat.enterprise-agent.home.empty.description": "利用可能なアプリとコンテキストを確認し、状況を説明して、意見や計画を準備できます。",
  "chat.enterprise-agent.home.suggestion.attention.label": "今、注意すべきことは？",
  "chat.enterprise-agent.home.suggestion.context.label": "現在のコンテキストを説明して",
  "setup.personal-agent.setup.title": "パーソナルエージェントを設定",
  "setup.personal-agent.setup.description": "次の手順で AI サービスを接続します。開始に必要な選択肢だけを表示します。",
  "setup.personal-agent.setup.step.provider.title": "AI サービスを選択",
  "setup.personal-agent.setup.step.provider.description": "パーソナルエージェントが使用するサービスを選択します。まだインストールしていない場合は、利用可能な AI サービスを参照できます。",
  "setup.personal-agent.setup.step.provider.status.current": "今すぐ選択",
  "setup.personal-agent.setup.step.provider.status.complete": "完了",
  "setup.personal-agent.setup.step.provider.status.pending": "待機中",
  "setup.personal-agent.setup.step.credentials.title": "サービスを接続",
  "setup.personal-agent.setup.step.credentials.description": "選択したサービスに必要な認証情報とモデル設定を入力します。",
  "setup.personal-agent.setup.step.credentials.status.current": "今すぐ接続",
  "setup.personal-agent.setup.step.credentials.status.complete": "完了",
  "setup.personal-agent.setup.step.credentials.status.pending": "待機中",
  "setup.personal-agent.setup.step.credentials.status.blocked": "待機中",
  "setup.personal-agent.setup.step.readiness.title": "接続を確認",
  "setup.personal-agent.setup.step.readiness.description": "パーソナルエージェントが選択したサービスに接続し、利用できることを確認します。",
  "setup.personal-agent.setup.step.readiness.status.current": "今すぐ確認",
  "setup.personal-agent.setup.step.readiness.status.complete": "完了",
  "setup.personal-agent.setup.step.readiness.status.blocked": "待機中",
  "setup.personal-agent.setup.step.readiness.status.error": "対応が必要",
  "setup.personal-agent.setup.step.ready.title": "利用できます",
  "setup.personal-agent.setup.step.ready.description": "設定が完了しました。パーソナルエージェントを使い始められます。",
  "setup.personal-agent.setup.step.ready.status.complete": "完了",
  "setup.personal-agent.setup.step.ready.status.blocked": "待機中",
  "setup.personal-agent.setup.action.choose-provider.label": "AI サービスを選択",
  "setup.personal-agent.setup.action.open-provider-catalog.label": "AI サービスを探す",
  "setup.personal-agent.setup.action.configure-provider.label": "サービスを接続",
  "setup.personal-agent.setup.action.open-agent.label": "パーソナルエージェントを開始",
  "setup.personal-agent.setup.action.provider-status.label": "接続の詳細",
  "setup.personal-agent.setup.action.check-provider-status.label": "接続を確認",
  "setup.personal-agent.setup.action.recheck-setup.label": "もう一度試す",
  "setup.personal-agent.setup.action.review-memory.label": "メモリーをレビュー",
  "setup.personal-agent.setup.action.memory-governance.label": "メモリガバナンス",
  "setup.personal-agent.setup.action.memory-source-health.label": "メモリソースの状態",
  "setup.personal-agent.setup.action.agent-quality.label": "パーソナルエージェント品質",
  "setup.personal-agent.setup.action.agent-follow-ups.label": "パーソナルエージェントのフォローアップ",
  "review.personal-agent.memory-review.technicalDetails.label": "技術情報",
  "review.personal-agent.memory-review.technicalDetail.proposalId.label": "提案 ID",
  "review.personal-agent.memory-review.technicalDetail.contextId.label": "コンテキスト ID",
  "review.personal-agent.memory-review.technicalDetail.revisionId.label": "リビジョン ID",
  "review.personal-agent.memory-review.technicalDetail.evidenceQuality.label": "証拠品質",
  "review.personal-agent.memory-review.technicalDetail.evidenceReference.label": "証拠参照",
  "review.personal-agent.memory-review.technicalDetail.sourceId.label": "ソース ID",
  "review.personal-agent.memory-review.technicalDetail.sourceType.label": "ソース種別",
  "review.personal-agent.memory-review.technicalDetail.sourceTrust.label": "ソース信頼レベル",
  "review.personal-agent.memory-review.technicalDetail.trustPolicyId.label": "信頼ポリシー ID",
  "review.personal-agent.memory-review.technicalDetail.reviewSignal.label": "レビューシグナル",
  "review.personal-agent.memory-review.technicalDetail.relatedMemoryId.label": "関連メモリー ID",
  "review.personal-agent.memory-review.technicalDetail.signalExplanation.label": "シグナル説明",
  "review.personal-agent.memory-review.technicalDetail.duplicateMemoryId.label": "重複メモリー ID",
  "review.personal-agent.memory-review.technicalDetail.canonicalMemoryId.label": "保持メモリー ID",
  "review.personal-agent.memory-review.field.reason.label": "提案理由",
  "review.personal-agent.memory-review.evidence.reference.title": "証拠",
  "review.personal-agent.memory-review.evidence.reference.source": "参照済み証拠",
  "review.personal-agent.memory-review.evidence.reference-unverified.title": "証拠",
  "review.personal-agent.memory-review.evidence.reference-unverified.source": "未検証の証拠",
  "review.personal-agent.memory-review.evidence.source-host-verified.source": "検証済みソース",
  "review.personal-agent.memory-review.evidence.source-declared.source": "申告済みソース",
  "review.personal-agent.memory-review.evidence.source-unverified.source": "未検証ソース",
  "review.personal-agent.memory-review.evidence.source-host-verified-generic.title": "証拠ソース",
  "review.personal-agent.memory-review.evidence.source-host-verified-generic.source": "検証済みソース",
  "review.personal-agent.memory-review.evidence.source-declared-generic.title": "証拠ソース",
  "review.personal-agent.memory-review.evidence.source-declared-generic.source": "申告済みソース",
  "review.personal-agent.memory-review.evidence.source-unverified-generic.title": "証拠ソース",
  "review.personal-agent.memory-review.evidence.source-unverified-generic.source": "未検証ソース",
  "review.personal-agent.memory-review.evidence.signal-potential-duplicate.title": "重複の可能性",
  "review.personal-agent.memory-review.evidence.signal-potential-duplicate.source": "レビューシグナル",
  "review.personal-agent.memory-review.evidence.signal-potential-contradiction.title": "矛盾の可能性",
  "review.personal-agent.memory-review.evidence.signal-potential-contradiction.source": "レビューシグナル",
  "review.personal-agent.memory-review.evidence.signal-supersession-candidate.title": "既存メモリーを置き換える可能性",
  "review.personal-agent.memory-review.evidence.signal-supersession-candidate.source": "レビューシグナル",
  "review.personal-agent.memory-review.item.canonicalization.title": "重複の可能性を確認",
  "review.personal-agent.memory-review.item.canonicalization.summary": "承認すると、重複項目は通常検索から非表示になり、既存メモリーはそのまま残ります。メモリー本文は削除されません。",
  "review.personal-agent.memory-review.evidence.canonicalization-duplicate.source": "非表示にする重複項目",
  "review.personal-agent.memory-review.evidence.canonicalization-canonical.source": "保持するメモリー",
  "review.personal-agent.memory-review.action.accept-canonicalization.label": "重複を確認",
  "review.personal-agent.memory-review.action.reject-canonicalization.label": "両方を保持",
};

const zhTwMessages = {
  "workbench.activity.label": "個人代理",
  "review.personal-agent.memory-review.title": "記憶審核",
  "review.personal-agent.memory-review.description": "決定哪些候選知識值得成為長期記憶。審核提示只是建議，每一次接受或拒絕都由你決定。",
  "review.personal-agent.memory-review.empty": "目前沒有需要審核的記憶提案。",
  "review.personal-agent.memory-review.status.pending.label": "待審核",
  "review.personal-agent.memory-review.status.attention.label": "需要關注",
  "review.personal-agent.memory-review.status.accepted.label": "已接受",
  "review.personal-agent.memory-review.status.rejected.label": "已拒絕",
  "review.personal-agent.memory-review.metric.confidence.label": "信心度",
  "review.personal-agent.memory-review.metric.evidence.label": "證據",
  "review.personal-agent.memory-review.metric.source-trust-host-verified.label": "Host 已驗證來源",
  "review.personal-agent.memory-review.metric.source-trust-declared.label": "已聲明來源",
  "review.personal-agent.memory-review.metric.source-trust-unverified.label": "未驗證來源",
  "review.personal-agent.memory-review.metric.conflicts.label": "審核訊號",
  "review.personal-agent.memory-review.metric.context.label": "內容環境",
  "review.personal-agent.memory-review.field.kind.label": "類型",
  "review.personal-agent.memory-review.field.kind.option.FACT.label": "事實",
  "review.personal-agent.memory-review.field.kind.option.CLAIM.label": "主張",
  "review.personal-agent.memory-review.field.kind.option.EXPERIENCE.label": "經驗",
  "review.personal-agent.memory-review.field.kind.option.PRACTICE.label": "實務",
  "review.personal-agent.memory-review.field.summary.label": "摘要",
  "review.personal-agent.memory-review.action.save.label": "儲存編輯",
  "review.personal-agent.memory-review.action.accept.label": "接受",
  "review.personal-agent.memory-review.action.reject.label": "拒絕",
  "navigation.enterprise-agent.nav.label": "個人代理",
  "page.enterprise-agent.home.title": "個人代理",
  "page.enterprise-agent.setup.title": "個人代理設定",
  "chat.enterprise-agent.home.composer.placeholder": "詢問問題或描述任務",
  "chat.enterprise-agent.home.composer.sendLabel": "傳送",
  "chat.enterprise-agent.home.context.label": "目前內容環境",
  "chat.enterprise-agent.home.context.selector.ariaLabel": "選擇內容環境",
  "chat.enterprise-agent.home.context.option.personal.label": "個人",
  "chat.enterprise-agent.home.readiness.ready.label": "就緒",
  "chat.enterprise-agent.home.readiness.ready.message": "個人代理已就緒。",
  "chat.enterprise-agent.home.readiness.setup-required.label": "需要設定",
  "chat.enterprise-agent.home.readiness.setup-required.message": "使用個人代理前，請先連接 AI 服務。",
  "chat.enterprise-agent.home.readiness.degraded.label": "效能下降",
  "chat.enterprise-agent.home.readiness.degraded.message": "已連接的 AI 服務需要處理。",
  "chat.enterprise-agent.home.readiness.unavailable.label": "無法使用",
  "chat.enterprise-agent.home.readiness.unavailable.message": "已連接的 AI 服務目前無法使用。",
  "chat.enterprise-agent.home.action.open-setup.label": "開啟設定",
  "chat.enterprise-agent.home.empty.title": "我可以幫你做什麼？",
  "chat.enterprise-agent.home.empty.description": "我可以查看可用應用與內容環境、說明目前情況，並準備意見或方案。",
  "chat.enterprise-agent.home.suggestion.attention.label": "現在有哪些事情需要我關注？",
  "chat.enterprise-agent.home.suggestion.context.label": "說明我目前的內容環境",
  "setup.personal-agent.setup.title": "設定個人代理",
  "setup.personal-agent.setup.description": "依照以下步驟連接 AI 服務。這裡只顯示開始使用所需的必要選項。",
  "setup.personal-agent.setup.step.provider.title": "選擇 AI 服務",
  "setup.personal-agent.setup.step.provider.description": "選擇個人代理要使用的服務。如果尚未安裝，可瀏覽可用的 AI 服務。",
  "setup.personal-agent.setup.step.provider.status.current": "現在選擇",
  "setup.personal-agent.setup.step.provider.status.complete": "完成",
  "setup.personal-agent.setup.step.provider.status.pending": "等待",
  "setup.personal-agent.setup.step.credentials.title": "連接服務",
  "setup.personal-agent.setup.step.credentials.description": "填寫所選服務要求的憑證與模型設定。",
  "setup.personal-agent.setup.step.credentials.status.current": "現在連接",
  "setup.personal-agent.setup.step.credentials.status.complete": "完成",
  "setup.personal-agent.setup.step.credentials.status.pending": "等待",
  "setup.personal-agent.setup.step.credentials.status.blocked": "等待",
  "setup.personal-agent.setup.step.readiness.title": "檢查連接",
  "setup.personal-agent.setup.step.readiness.description": "系統會確認個人代理能夠連接並使用所選服務。",
  "setup.personal-agent.setup.step.readiness.status.current": "現在檢查",
  "setup.personal-agent.setup.step.readiness.status.complete": "完成",
  "setup.personal-agent.setup.step.readiness.status.blocked": "等待",
  "setup.personal-agent.setup.step.readiness.status.error": "需要處理",
  "setup.personal-agent.setup.step.ready.title": "可以使用了",
  "setup.personal-agent.setup.step.ready.description": "設定已完成，現在可以開始使用個人代理。",
  "setup.personal-agent.setup.step.ready.status.complete": "完成",
  "setup.personal-agent.setup.step.ready.status.blocked": "等待",
  "setup.personal-agent.setup.action.choose-provider.label": "選擇 AI 服務",
  "setup.personal-agent.setup.action.open-provider-catalog.label": "瀏覽 AI 服務",
  "setup.personal-agent.setup.action.configure-provider.label": "連接服務",
  "setup.personal-agent.setup.action.open-agent.label": "開始使用個人代理",
  "setup.personal-agent.setup.action.provider-status.label": "連接詳情",
  "setup.personal-agent.setup.action.check-provider-status.label": "檢查連接",
  "setup.personal-agent.setup.action.recheck-setup.label": "再試一次",
  "setup.personal-agent.setup.action.review-memory.label": "審核記憶",
  "setup.personal-agent.setup.action.memory-governance.label": "記憶治理",
  "setup.personal-agent.setup.action.memory-source-health.label": "記憶來源健康狀態",
  "setup.personal-agent.setup.action.agent-quality.label": "個人代理品質",
  "setup.personal-agent.setup.action.agent-follow-ups.label": "個人代理後續事項",
  "review.personal-agent.memory-review.technicalDetails.label": "技術詳情",
  "review.personal-agent.memory-review.technicalDetail.proposalId.label": "提案 ID",
  "review.personal-agent.memory-review.technicalDetail.contextId.label": "內容環境 ID",
  "review.personal-agent.memory-review.technicalDetail.revisionId.label": "修訂 ID",
  "review.personal-agent.memory-review.technicalDetail.evidenceQuality.label": "證據品質",
  "review.personal-agent.memory-review.technicalDetail.evidenceReference.label": "證據引用",
  "review.personal-agent.memory-review.technicalDetail.sourceId.label": "來源 ID",
  "review.personal-agent.memory-review.technicalDetail.sourceType.label": "來源類型",
  "review.personal-agent.memory-review.technicalDetail.sourceTrust.label": "來源可信層級",
  "review.personal-agent.memory-review.technicalDetail.trustPolicyId.label": "信任政策 ID",
  "review.personal-agent.memory-review.technicalDetail.reviewSignal.label": "審核訊號",
  "review.personal-agent.memory-review.technicalDetail.relatedMemoryId.label": "相關記憶 ID",
  "review.personal-agent.memory-review.technicalDetail.signalExplanation.label": "訊號說明",
  "review.personal-agent.memory-review.technicalDetail.duplicateMemoryId.label": "重複記憶 ID",
  "review.personal-agent.memory-review.technicalDetail.canonicalMemoryId.label": "保留記憶 ID",
  "review.personal-agent.memory-review.field.reason.label": "建議原因",
  "review.personal-agent.memory-review.evidence.reference.title": "證據",
  "review.personal-agent.memory-review.evidence.reference.source": "已引用證據",
  "review.personal-agent.memory-review.evidence.reference-unverified.title": "證據",
  "review.personal-agent.memory-review.evidence.reference-unverified.source": "未驗證證據",
  "review.personal-agent.memory-review.evidence.source-host-verified.source": "已驗證來源",
  "review.personal-agent.memory-review.evidence.source-declared.source": "已聲明來源",
  "review.personal-agent.memory-review.evidence.source-unverified.source": "未驗證來源",
  "review.personal-agent.memory-review.evidence.source-host-verified-generic.title": "證據來源",
  "review.personal-agent.memory-review.evidence.source-host-verified-generic.source": "已驗證來源",
  "review.personal-agent.memory-review.evidence.source-declared-generic.title": "證據來源",
  "review.personal-agent.memory-review.evidence.source-declared-generic.source": "已聲明來源",
  "review.personal-agent.memory-review.evidence.source-unverified-generic.title": "證據來源",
  "review.personal-agent.memory-review.evidence.source-unverified-generic.source": "未驗證來源",
  "review.personal-agent.memory-review.evidence.signal-potential-duplicate.title": "可能重複",
  "review.personal-agent.memory-review.evidence.signal-potential-duplicate.source": "審核提示",
  "review.personal-agent.memory-review.evidence.signal-potential-contradiction.title": "可能矛盾",
  "review.personal-agent.memory-review.evidence.signal-potential-contradiction.source": "審核提示",
  "review.personal-agent.memory-review.evidence.signal-supersession-candidate.title": "可能取代既有記憶",
  "review.personal-agent.memory-review.evidence.signal-supersession-candidate.source": "審核提示",
  "review.personal-agent.memory-review.item.canonicalization.title": "審核可能重複的記憶",
  "review.personal-agent.memory-review.item.canonicalization.summary": "接受後，重複項目會從一般檢索中隱藏，既有記憶會繼續保留。不會刪除任何記憶正文。",
  "review.personal-agent.memory-review.evidence.canonicalization-duplicate.source": "將隱藏的重複項目",
  "review.personal-agent.memory-review.evidence.canonicalization-canonical.source": "繼續保留的記憶",
  "review.personal-agent.memory-review.action.accept-canonicalization.label": "確認重複",
  "review.personal-agent.memory-review.action.reject-canonicalization.label": "兩項都保留",
};

export const enterpriseAgentPackage: PackageManifestV010 = {
  contractVersion: "0.1.0",
  packageId: ENTERPRISE_AGENT_PACKAGE_ID,
  displayName: "Personal Agent",
  version: "0.1.0",
  type: "AGENT",
  features: [
    {
      contractVersion: "0.1.0",
      featureId: ENTERPRISE_AGENT_FEATURE_ID,
      packageId: ENTERPRISE_AGENT_PACKAGE_ID,
      version: "0.1.0",
      activationScope: "INSTALLATION",
      defaultActivation: true,
      providesCapabilities: [
        "agent.personal",
        "agent.personal.tool-discovery",
        "agent.enterprise",
        "agent.enterprise.app-manager-tools",
        "agent.enterprise.tool-discovery"
      ],
      contributions: [
        {
          kind: "eidos.experience",
          manifest: {
            contractVersion: "0.1.0",
            experienceId: "enterprise-agent",
            packageId: ENTERPRISE_AGENT_PACKAGE_ID,
            featureId: ENTERPRISE_AGENT_FEATURE_ID,
            defaultRoute: "/enterprise-agent",
            pages: [
              {
                id: "enterprise-agent.home",
                title: "Personal Agent",
                source: ENTERPRISE_AGENT_PAGE_SOURCE
              },
              {
                id: "enterprise-agent.mobile-home",
                title: "Personal Agent",
                source: ENTERPRISE_AGENT_MOBILE_PAGE_SOURCE
              },
              {
                id: "enterprise-agent.setup",
                title: "Personal Agent setup",
                source: ENTERPRISE_AGENT_SETUP_PAGE_SOURCE
              },
              {
                id: "enterprise-agent.memory-review",
                title: "Memory review",
                source: ENTERPRISE_AGENT_MEMORY_REVIEW_PAGE_SOURCE
              },
              {
                id: "enterprise-agent.quality",
                title: "Personal Agent quality",
                source: ENTERPRISE_AGENT_QUALITY_PAGE_SOURCE
              },
              {
                id: "enterprise-agent.quality-review",
                title: "Personal Agent quality review",
                source: ENTERPRISE_AGENT_QUALITY_REVIEW_PAGE_SOURCE
              },
              {
                id: "enterprise-agent.follow-ups",
                title: "Personal Agent follow-ups",
                source: ENTERPRISE_AGENT_FOLLOW_UP_PAGE_SOURCE
              },
              {
                id: "enterprise-agent.mobile-follow-ups",
                title: "My follow-ups",
                source: ENTERPRISE_AGENT_MOBILE_FOLLOW_UP_PAGE_SOURCE
              }
            ],
            routes: [
              {
                id: "enterprise-agent.home",
                semanticId: "enterprise-agent.home",
                surfaceId: "enterprise-agent.desktop",
                path: "/enterprise-agent",
                pageId: "enterprise-agent.home"
              },
              {
                id: "enterprise-agent.mobile-home",
                semanticId: "enterprise-agent.home",
                surfaceId: "enterprise-agent.mobile-task",
                path: "/m/enterprise-agent",
                pageId: "enterprise-agent.mobile-home"
              },
              {
                id: "enterprise-agent.setup",
                semanticId: "enterprise-agent.setup",
                surfaceId: "enterprise-agent.desktop",
                path: "/enterprise-agent/setup",
                pageId: "enterprise-agent.setup"
              },
              {
                id: "enterprise-agent.memory-review",
                semanticId: "enterprise-agent.memory-review",
                surfaceId: "enterprise-agent.desktop",
                path: "/enterprise-agent/memory",
                pageId: "enterprise-agent.memory-review"
              },
              {
                id: "enterprise-agent.mobile-memory-review",
                semanticId: "enterprise-agent.memory-review",
                surfaceId: "enterprise-agent.mobile-task",
                path: "/m/enterprise-agent/memory",
                pageId: "enterprise-agent.memory-review"
              },
              {
                id: "enterprise-agent.quality",
                semanticId: "enterprise-agent.quality",
                surfaceId: "enterprise-agent.desktop",
                path: "/enterprise-agent/quality",
                pageId: "enterprise-agent.quality"
              },
              {
                id: "enterprise-agent.quality-review",
                semanticId: "enterprise-agent.quality-review",
                surfaceId: "enterprise-agent.desktop",
                path: "/enterprise-agent/quality/review",
                pageId: "enterprise-agent.quality-review"
              },
              {
                id: "enterprise-agent.follow-ups",
                semanticId: "enterprise-agent.follow-ups",
                surfaceId: "enterprise-agent.desktop",
                path: "/enterprise-agent/follow-ups",
                pageId: "enterprise-agent.follow-ups"
              },
              {
                id: "enterprise-agent.mobile-follow-ups",
                semanticId: "enterprise-agent.follow-ups",
                surfaceId: "enterprise-agent.mobile-task",
                path: "/m/enterprise-agent/follow-ups",
                pageId: "enterprise-agent.mobile-follow-ups"
              }
            ],
            navigation: [
              {
                id: "enterprise-agent.nav",
                label: "Personal Agent",
                route: "/enterprise-agent",
                order: 10,
                surfaceIds: ["enterprise-agent.desktop"]
              }
            ],
            surfaces: [
              {
                id: "enterprise-agent.desktop",
                target: "DESKTOP_WORKBENCH",
                support: "FULL",
                entryRoute: "/enterprise-agent"
              },
              {
                id: "enterprise-agent.mobile-task",
                target: "MOBILE_TASK",
                support: "TASK_FOCUSED",
                entryRoute: "/m/enterprise-agent",
                fallbackSurfaceId: "enterprise-agent.desktop"
              },
              {
                id: "enterprise-agent.mobile-read",
                target: "MOBILE_READ",
                support: "UNSUPPORTED",
                fallbackSurfaceId: "enterprise-agent.desktop"
              }
            ]
          }
        },
        {
          kind: "eidos.workbench-activity",
          activity: {
            contractVersion: "0.1.0",
            id: "enterprise-agent",
            title: "Personal Agent",
            icon: "agent",
            kind: "side-route",
            route: "/enterprise-agent",
            order: 20,
            localization: {
              namespace: ENTERPRISE_AGENT_PACKAGE_ID,
              key: "workbench.activity.label"
            }
          }
        },
        {
          kind: "eidos.workbench-home-item",
          item: {
            contractVersion: "0.1.0",
            id: "enterprise-agent.workbench.my-work",
            title: "My Work",
            description: "Open Personal Agent follow-ups and governed review work.",
            section: "MY_WORK",
            route: "/enterprise-agent/follow-ups",
            order: 10
          }
        },
        {
          kind: "eidos.workbench-home-item",
          item: {
            contractVersion: "0.1.0",
            id: "enterprise-agent.workbench.agent",
            title: "Personal Agent",
            description: "Reason, search and operate through the same Host-governed capabilities.",
            section: "PERSONAL_AGENT",
            route: "/enterprise-agent",
            order: 90
          }
        },
        ...([
          ["en", enMessages],
          ["zh-CN", zhCnMessages],
          ["ja", jaMessages],
          ["zh-TW", zhTwMessages]
        ] as const).map(([locale, messages]) => ({
          kind: "eidos.localization-bundle" as const,
          bundle: {
            contractVersion: "0.1.0" as const,
            namespace: ENTERPRISE_AGENT_PACKAGE_ID,
            locale,
            messages
          }
        }))
      ]
    }
  ]
};

export const enterpriseAgentExperienceAssets = new Map<string, unknown>([
  [ENTERPRISE_AGENT_MOBILE_PAGE_SOURCE, {
    contractVersion: "0.1.0",
    kind: "chat",
    id: "enterprise-agent.mobile-home",
    title: "Personal Agent",
    command: {
      code: "enterprise-agent.chat",
      inputVersion: "0.1.0"
    },
    composer: {
      key: "message",
      placeholder: "Ask or describe a task",
      sendLabel: "Send"
    },
    emptyState: "Ask Personal Agent what needs your attention or what you want to accomplish.",
    metadata: {
      packageId: ENTERPRISE_AGENT_PACKAGE_ID,
      featureId: ENTERPRISE_AGENT_FEATURE_ID,
      surface: {
        target: "MOBILE_TASK",
        interaction: "TASK_FOCUSED"
      },
      llm: {
        requiredCapability: "llm.inference",
        integrationStatus: "PROVIDER_RESOLVED_AT_RUNTIME"
      }
    }
  }],
  [ENTERPRISE_AGENT_PAGE_SOURCE, {
    contractVersion: "0.1.0",
    kind: "chat",
    id: "enterprise-agent.home",
    title: "Personal Agent",
    command: {
      code: "enterprise-agent.chat",
      inputVersion: "0.1.0"
    },
    composer: {
      key: "message",
      placeholder: "Tell Personal Agent what you want to accomplish",
      sendLabel: "Send"
    },
    emptyState: "Ask Personal Agent to inspect, explain or prepare an opinion or change.",
    metadata: {
      packageId: ENTERPRISE_AGENT_PACKAGE_ID,
      featureId: ENTERPRISE_AGENT_FEATURE_ID,
      convergence: {
        historicalProject: "Experience Compiler (EC)",
        sourceRepository: "jiangxng/Experience-Compiler",
        sourceRelease: "1.0.1",
        targetIdentity: "Personal Agent"
      },
      llm: {
        requiredCapability: "llm.inference",
        integrationStatus: "PROVIDER_RESOLVED_AT_RUNTIME"
      },
      preservedAssets: [
        "knowledge",
        "memory",
        "learning",
        "research",
        "context-compiler",
        "provenance-lineage",
        "industry-packs",
        "model-replacement"
      ]
    }
  }]
]);
