import type { PackageManifestV010 } from "../../contracts/package.js";

export const ENTERPRISE_AGENT_PACKAGE_ID = "enterprise-agent";
export const ENTERPRISE_AGENT_FEATURE_ID = "enterprise-agent.default";
export const ENTERPRISE_AGENT_PAGE_SOURCE = "app://enterprise-agent/pages/home";
export const ENTERPRISE_AGENT_SETUP_PAGE_SOURCE = "app://enterprise-agent/pages/setup";
export const ENTERPRISE_AGENT_MEMORY_REVIEW_PAGE_SOURCE = "app://enterprise-agent/pages/memory-review";
export const ENTERPRISE_AGENT_QUALITY_PAGE_SOURCE = "app://enterprise-agent/pages/quality";
export const ENTERPRISE_AGENT_QUALITY_REVIEW_PAGE_SOURCE = "app://enterprise-agent/pages/quality-review";

const enMessages = {
  "workbench.activity.label": "Personal Agent",
  "review.personal-agent.memory-review.title": "Memory review",
  "review.personal-agent.memory-review.description": "Review, edit, accept or reject proposed durable knowledge before it becomes Context Memory.",
  "review.personal-agent.memory-review.empty": "No Memory proposals need review.",
  "review.personal-agent.memory-review.status.pending.label": "Pending",
  "review.personal-agent.memory-review.status.attention.label": "Needs attention",
  "review.personal-agent.memory-review.status.accepted.label": "Accepted",
  "review.personal-agent.memory-review.status.rejected.label": "Rejected",
  "review.personal-agent.memory-review.metric.confidence.label": "Proposed confidence",
  "review.personal-agent.memory-review.metric.evidence.label": "Evidence refs",
  "review.personal-agent.memory-review.metric.source-trust-host-verified.label": "Host-verified sources",
  "review.personal-agent.memory-review.metric.source-trust-declared.label": "Declared sources",
  "review.personal-agent.memory-review.metric.source-trust-unverified.label": "Unverified sources",
  "review.personal-agent.memory-review.metric.conflicts.label": "Review signals",
  "review.personal-agent.memory-review.metric.context.label": "Context",
  "review.personal-agent.memory-review.field.kind.label": "Kind",
  "review.personal-agent.memory-review.field.kind.option.FACT.label": "Fact",
  "review.personal-agent.memory-review.field.kind.option.CLAIM.label": "Claim",
  "review.personal-agent.memory-review.field.kind.option.EXPERIENCE.label": "Experience",
  "review.personal-agent.memory-review.field.kind.option.PRACTICE.label": "Practice",
  "review.personal-agent.memory-review.field.summary.label": "Summary",
  "review.personal-agent.memory-review.action.save.label": "Save edit",
  "review.personal-agent.memory-review.action.accept.label": "Accept",
  "review.personal-agent.memory-review.action.reject.label": "Reject",
  "navigation.enterprise-agent.nav.label": "Personal Agent",
  "page.enterprise-agent.home.title": "Personal Agent",
  "page.enterprise-agent.setup.title": "Personal Agent setup",
  "chat.enterprise-agent.home.composer.placeholder": "Ask or describe a task",
  "chat.enterprise-agent.home.composer.sendLabel": "Send",
  "chat.enterprise-agent.home.context.label": "Current context",
  "chat.enterprise-agent.home.context.selector.ariaLabel": "Choose context",
  "chat.enterprise-agent.home.readiness.ready.label": "Ready",
  "chat.enterprise-agent.home.readiness.ready.message": "Personal Agent is ready.",
  "chat.enterprise-agent.home.readiness.setup-required.label": "Needs setup",
  "chat.enterprise-agent.home.readiness.setup-required.message": "Complete Provider setup before using Personal Agent.",
  "chat.enterprise-agent.home.readiness.degraded.label": "Degraded",
  "chat.enterprise-agent.home.readiness.degraded.message": "The selected LLM Provider is degraded.",
  "chat.enterprise-agent.home.readiness.unavailable.label": "Unavailable",
  "chat.enterprise-agent.home.readiness.unavailable.message": "The selected LLM Provider is unavailable.",
  "chat.enterprise-agent.home.action.open-setup.label": "Open setup",
  "chat.enterprise-agent.home.empty.title": "How can I help?",
  "chat.enterprise-agent.home.empty.description": "I can inspect your available apps and Context, explain what is happening, and prepare an opinion or plan.",
  "chat.enterprise-agent.home.suggestion.attention.label": "What needs my attention?",
  "chat.enterprise-agent.home.suggestion.context.label": "Explain my current context",
  "setup.personal-agent.setup.title": "Personal Agent setup",
  "setup.personal-agent.setup.description": "Complete the required platform-owned Provider steps. Personal Agent does not store Provider credentials.",
  "setup.personal-agent.setup.step.provider.title": "LLM Provider",
  "setup.personal-agent.setup.step.provider.description": "Select or install a Provider for llm.inference.",
  "setup.personal-agent.setup.step.provider.status.current": "Required",
  "setup.personal-agent.setup.step.provider.status.complete": "Complete",
  "setup.personal-agent.setup.step.provider.status.pending": "Waiting",
  "setup.personal-agent.setup.step.credentials.title": "Provider configuration",
  "setup.personal-agent.setup.step.credentials.description": "Configure credentials and Provider-owned runtime settings in the Provider Settings surface.",
  "setup.personal-agent.setup.step.credentials.status.current": "Required",
  "setup.personal-agent.setup.step.credentials.status.complete": "Complete",
  "setup.personal-agent.setup.step.credentials.status.pending": "Waiting",
  "setup.personal-agent.setup.step.credentials.status.blocked": "Waiting",
  "setup.personal-agent.setup.step.readiness.title": "Provider readiness",
  "setup.personal-agent.setup.step.readiness.description": "The Host verifies that Provider resolution and runtime readiness are usable.",
  "setup.personal-agent.setup.step.readiness.status.current": "Checking",
  "setup.personal-agent.setup.step.readiness.status.complete": "Complete",
  "setup.personal-agent.setup.step.readiness.status.blocked": "Waiting",
  "setup.personal-agent.setup.step.readiness.status.error": "Attention required",
  "setup.personal-agent.setup.step.ready.title": "Ready",
  "setup.personal-agent.setup.step.ready.description": "Personal Agent can now use the selected LLM Provider.",
  "setup.personal-agent.setup.step.ready.status.complete": "Complete",
  "setup.personal-agent.setup.step.ready.status.blocked": "Waiting",
  "setup.personal-agent.setup.action.choose-provider.label": "Choose Provider",
  "setup.personal-agent.setup.action.open-provider-catalog.label": "Open Provider catalog",
  "setup.personal-agent.setup.action.configure-provider.label": "Configure Provider",
  "setup.personal-agent.setup.action.open-agent.label": "Open Personal Agent",
  "setup.personal-agent.setup.action.provider-status.label": "Provider status",
  "setup.personal-agent.setup.action.check-provider-status.label": "Check Provider status",
  "setup.personal-agent.setup.action.recheck-setup.label": "Recheck setup",
  "setup.personal-agent.setup.action.review-memory.label": "Review Memory",
  "setup.personal-agent.setup.action.memory-governance.label": "Memory Governance",
  "setup.personal-agent.setup.action.memory-source-health.label": "Memory Source Health",
  "setup.personal-agent.setup.action.agent-quality.label": "Personal Agent Quality"
};

const zhCnMessages = {
  "workbench.activity.label": "个人代理",
  "review.personal-agent.memory-review.title": "记忆审核",
  "review.personal-agent.memory-review.description": "在候选知识成为 Context Memory 前进行查看、编辑、接受或拒绝。",
  "review.personal-agent.memory-review.empty": "当前没有需要审核的记忆提案。",
  "review.personal-agent.memory-review.status.pending.label": "待审核",
  "review.personal-agent.memory-review.status.attention.label": "需要关注",
  "review.personal-agent.memory-review.status.accepted.label": "已接受",
  "review.personal-agent.memory-review.status.rejected.label": "已拒绝",
  "review.personal-agent.memory-review.metric.confidence.label": "建议置信度",
  "review.personal-agent.memory-review.metric.evidence.label": "证据引用",
  "review.personal-agent.memory-review.metric.source-trust-host-verified.label": "Host 已验证来源",
  "review.personal-agent.memory-review.metric.source-trust-declared.label": "已声明来源",
  "review.personal-agent.memory-review.metric.source-trust-unverified.label": "未验证来源",
  "review.personal-agent.memory-review.metric.conflicts.label": "审核信号",
  "review.personal-agent.memory-review.metric.context.label": "上下文",
  "review.personal-agent.memory-review.field.kind.label": "类型",
  "review.personal-agent.memory-review.field.kind.option.FACT.label": "事实",
  "review.personal-agent.memory-review.field.kind.option.CLAIM.label": "主张",
  "review.personal-agent.memory-review.field.kind.option.EXPERIENCE.label": "经验",
  "review.personal-agent.memory-review.field.kind.option.PRACTICE.label": "实践",
  "review.personal-agent.memory-review.field.summary.label": "摘要",
  "review.personal-agent.memory-review.action.save.label": "保存编辑",
  "review.personal-agent.memory-review.action.accept.label": "接受",
  "review.personal-agent.memory-review.action.reject.label": "拒绝",
  "navigation.enterprise-agent.nav.label": "个人代理",
  "page.enterprise-agent.home.title": "个人代理",
  "page.enterprise-agent.setup.title": "个人代理设置",
  "chat.enterprise-agent.home.composer.placeholder": "询问问题或描述任务",
  "chat.enterprise-agent.home.composer.sendLabel": "发送",
  "chat.enterprise-agent.home.context.label": "当前上下文",
  "chat.enterprise-agent.home.context.selector.ariaLabel": "选择上下文",
  "chat.enterprise-agent.home.readiness.ready.label": "就绪",
  "chat.enterprise-agent.home.readiness.ready.message": "个人代理已就绪。",
  "chat.enterprise-agent.home.readiness.setup-required.label": "需要设置",
  "chat.enterprise-agent.home.readiness.setup-required.message": "使用个人代理前，请先完成 Provider 设置。",
  "chat.enterprise-agent.home.readiness.degraded.label": "性能下降",
  "chat.enterprise-agent.home.readiness.degraded.message": "当前 LLM Provider 处于降级状态。",
  "chat.enterprise-agent.home.readiness.unavailable.label": "不可用",
  "chat.enterprise-agent.home.readiness.unavailable.message": "当前 LLM Provider 不可用。",
  "chat.enterprise-agent.home.action.open-setup.label": "打开设置",
  "chat.enterprise-agent.home.empty.title": "我可以帮你做什么？",
  "chat.enterprise-agent.home.empty.description": "我可以查看可用应用和上下文，解释当前情况，并准备意见或方案。",
  "chat.enterprise-agent.home.suggestion.attention.label": "现在有哪些事情需要我关注？",
  "chat.enterprise-agent.home.suggestion.context.label": "解释我当前的上下文",
  "setup.personal-agent.setup.title": "个人代理设置",
  "setup.personal-agent.setup.description": "完成平台管理的 Provider 必要步骤。个人代理本身不保存 Provider 凭据。",
  "setup.personal-agent.setup.step.provider.title": "LLM Provider",
  "setup.personal-agent.setup.step.provider.description": "为 llm.inference 选择或安装 Provider。",
  "setup.personal-agent.setup.step.provider.status.current": "必需",
  "setup.personal-agent.setup.step.provider.status.complete": "完成",
  "setup.personal-agent.setup.step.provider.status.pending": "等待",
  "setup.personal-agent.setup.step.credentials.title": "Provider 配置",
  "setup.personal-agent.setup.step.credentials.description": "在 Provider 自己的设置界面配置凭据和运行参数。",
  "setup.personal-agent.setup.step.credentials.status.current": "必需",
  "setup.personal-agent.setup.step.credentials.status.complete": "完成",
  "setup.personal-agent.setup.step.credentials.status.pending": "等待",
  "setup.personal-agent.setup.step.credentials.status.blocked": "等待",
  "setup.personal-agent.setup.step.readiness.title": "Provider 就绪状态",
  "setup.personal-agent.setup.step.readiness.description": "Host 会验证 Provider 解析结果和运行时是否可用。",
  "setup.personal-agent.setup.step.readiness.status.current": "检查中",
  "setup.personal-agent.setup.step.readiness.status.complete": "完成",
  "setup.personal-agent.setup.step.readiness.status.blocked": "等待",
  "setup.personal-agent.setup.step.readiness.status.error": "需要处理",
  "setup.personal-agent.setup.step.ready.title": "就绪",
  "setup.personal-agent.setup.step.ready.description": "个人代理现在可以使用已选择的 LLM Provider。",
  "setup.personal-agent.setup.step.ready.status.complete": "完成",
  "setup.personal-agent.setup.step.ready.status.blocked": "等待",
  "setup.personal-agent.setup.action.choose-provider.label": "选择 Provider",
  "setup.personal-agent.setup.action.open-provider-catalog.label": "打开 Provider 目录",
  "setup.personal-agent.setup.action.configure-provider.label": "配置 Provider",
  "setup.personal-agent.setup.action.open-agent.label": "打开个人代理",
  "setup.personal-agent.setup.action.provider-status.label": "Provider 状态",
  "setup.personal-agent.setup.action.check-provider-status.label": "检查 Provider 状态",
  "setup.personal-agent.setup.action.recheck-setup.label": "重新检查设置",
  "setup.personal-agent.setup.action.review-memory.label": "审核记忆",
  "setup.personal-agent.setup.action.memory-governance.label": "记忆治理",
  "setup.personal-agent.setup.action.memory-source-health.label": "记忆来源健康状态",
  "setup.personal-agent.setup.action.agent-quality.label": "个人代理质量"
};

const jaMessages = {
  "workbench.activity.label": "パーソナルエージェント",
  "review.personal-agent.memory-review.title": "メモリーレビュー",
  "review.personal-agent.memory-review.description": "候補知識が Context Memory になる前に、確認・編集・承認・却下します。",
  "review.personal-agent.memory-review.empty": "レビューが必要なメモリー提案はありません。",
  "review.personal-agent.memory-review.status.pending.label": "レビュー待ち",
  "review.personal-agent.memory-review.status.attention.label": "要確認",
  "review.personal-agent.memory-review.status.accepted.label": "承認済み",
  "review.personal-agent.memory-review.status.rejected.label": "却下済み",
  "review.personal-agent.memory-review.metric.confidence.label": "提案信頼度",
  "review.personal-agent.memory-review.metric.evidence.label": "証拠参照",
  "review.personal-agent.memory-review.metric.source-trust-host-verified.label": "Host 検証済みソース",
  "review.personal-agent.memory-review.metric.source-trust-declared.label": "申告済みソース",
  "review.personal-agent.memory-review.metric.source-trust-unverified.label": "未検証ソース",
  "review.personal-agent.memory-review.metric.conflicts.label": "レビュー信号",
  "review.personal-agent.memory-review.metric.context.label": "コンテキスト",
  "review.personal-agent.memory-review.field.kind.label": "種類",
  "review.personal-agent.memory-review.field.kind.option.FACT.label": "事実",
  "review.personal-agent.memory-review.field.kind.option.CLAIM.label": "主張",
  "review.personal-agent.memory-review.field.kind.option.EXPERIENCE.label": "経験",
  "review.personal-agent.memory-review.field.kind.option.PRACTICE.label": "プラクティス",
  "review.personal-agent.memory-review.field.summary.label": "要約",
  "review.personal-agent.memory-review.action.save.label": "編集を保存",
  "review.personal-agent.memory-review.action.accept.label": "承認",
  "review.personal-agent.memory-review.action.reject.label": "却下",
  "navigation.enterprise-agent.nav.label": "パーソナルエージェント",
  "page.enterprise-agent.home.title": "パーソナルエージェント",
  "page.enterprise-agent.setup.title": "パーソナルエージェントのセットアップ",
  "chat.enterprise-agent.home.composer.placeholder": "質問またはタスクを入力してください",
  "chat.enterprise-agent.home.composer.sendLabel": "送信",
  "chat.enterprise-agent.home.context.label": "現在のコンテキスト",
  "chat.enterprise-agent.home.context.selector.ariaLabel": "コンテキストを選択",
  "chat.enterprise-agent.home.readiness.ready.label": "準備完了",
  "chat.enterprise-agent.home.readiness.ready.message": "パーソナルエージェントを利用できます。",
  "chat.enterprise-agent.home.readiness.setup-required.label": "セットアップが必要",
  "chat.enterprise-agent.home.readiness.setup-required.message": "パーソナルエージェントを使う前に Provider の設定を完了してください。",
  "chat.enterprise-agent.home.readiness.degraded.label": "低下",
  "chat.enterprise-agent.home.readiness.degraded.message": "選択した LLM Provider は低下状態です。",
  "chat.enterprise-agent.home.readiness.unavailable.label": "利用不可",
  "chat.enterprise-agent.home.readiness.unavailable.message": "選択した LLM Provider は利用できません。",
  "chat.enterprise-agent.home.action.open-setup.label": "セットアップを開く",
  "chat.enterprise-agent.home.empty.title": "何をお手伝いしましょうか？",
  "chat.enterprise-agent.home.empty.description": "利用可能なアプリとコンテキストを確認し、状況を説明して、意見や計画を準備できます。",
  "chat.enterprise-agent.home.suggestion.attention.label": "今、注意すべきことは？",
  "chat.enterprise-agent.home.suggestion.context.label": "現在のコンテキストを説明して",
  "setup.personal-agent.setup.title": "パーソナルエージェントのセットアップ",
  "setup.personal-agent.setup.description": "プラットフォームが管理する Provider の必要な手順を完了してください。パーソナルエージェントは Provider の認証情報を保存しません。",
  "setup.personal-agent.setup.step.provider.title": "LLM Provider",
  "setup.personal-agent.setup.step.provider.description": "llm.inference 用の Provider を選択またはインストールします。",
  "setup.personal-agent.setup.step.provider.status.current": "必須",
  "setup.personal-agent.setup.step.provider.status.complete": "完了",
  "setup.personal-agent.setup.step.provider.status.pending": "待機中",
  "setup.personal-agent.setup.step.credentials.title": "Provider 設定",
  "setup.personal-agent.setup.step.credentials.description": "Provider の設定画面で認証情報とランタイム設定を構成します。",
  "setup.personal-agent.setup.step.credentials.status.current": "必須",
  "setup.personal-agent.setup.step.credentials.status.complete": "完了",
  "setup.personal-agent.setup.step.credentials.status.pending": "待機中",
  "setup.personal-agent.setup.step.credentials.status.blocked": "待機中",
  "setup.personal-agent.setup.step.readiness.title": "Provider の準備状態",
  "setup.personal-agent.setup.step.readiness.description": "Host が Provider の解決結果とランタイムの利用可否を確認します。",
  "setup.personal-agent.setup.step.readiness.status.current": "確認中",
  "setup.personal-agent.setup.step.readiness.status.complete": "完了",
  "setup.personal-agent.setup.step.readiness.status.blocked": "待機中",
  "setup.personal-agent.setup.step.readiness.status.error": "対応が必要",
  "setup.personal-agent.setup.step.ready.title": "準備完了",
  "setup.personal-agent.setup.step.ready.description": "パーソナルエージェントは選択した LLM Provider を利用できます。",
  "setup.personal-agent.setup.step.ready.status.complete": "完了",
  "setup.personal-agent.setup.step.ready.status.blocked": "待機中",
  "setup.personal-agent.setup.action.choose-provider.label": "Provider を選択",
  "setup.personal-agent.setup.action.open-provider-catalog.label": "Provider カタログを開く",
  "setup.personal-agent.setup.action.configure-provider.label": "Provider を設定",
  "setup.personal-agent.setup.action.open-agent.label": "パーソナルエージェントを開く",
  "setup.personal-agent.setup.action.provider-status.label": "Provider の状態",
  "setup.personal-agent.setup.action.check-provider-status.label": "Provider の状態を確認",
  "setup.personal-agent.setup.action.recheck-setup.label": "セットアップを再確認",
  "setup.personal-agent.setup.action.review-memory.label": "メモリーをレビュー",
  "setup.personal-agent.setup.action.memory-governance.label": "メモリガバナンス",
  "setup.personal-agent.setup.action.memory-source-health.label": "メモリソースの状態",
  "setup.personal-agent.setup.action.agent-quality.label": "パーソナルエージェント品質"
};

const zhTwMessages = {
  "workbench.activity.label": "個人代理",
  "review.personal-agent.memory-review.title": "記憶審核",
  "review.personal-agent.memory-review.description": "在候選知識成為 Context Memory 前進行查看、編輯、接受或拒絕。",
  "review.personal-agent.memory-review.empty": "目前沒有需要審核的記憶提案。",
  "review.personal-agent.memory-review.status.pending.label": "待審核",
  "review.personal-agent.memory-review.status.attention.label": "需要關注",
  "review.personal-agent.memory-review.status.accepted.label": "已接受",
  "review.personal-agent.memory-review.status.rejected.label": "已拒絕",
  "review.personal-agent.memory-review.metric.confidence.label": "建議信心度",
  "review.personal-agent.memory-review.metric.evidence.label": "證據引用",
  "review.personal-agent.memory-review.metric.source-trust-host-verified.label": "Host 已驗證來源",
  "review.personal-agent.memory-review.metric.source-trust-declared.label": "已聲明來源",
  "review.personal-agent.memory-review.metric.source-trust-unverified.label": "未驗證來源",
  "review.personal-agent.memory-review.metric.conflicts.label": "審核訊號",
  "review.personal-agent.memory-review.metric.context.label": "內容環境",
  "review.personal-agent.memory-review.field.kind.label": "類型",
  "review.personal-agent.memory-review.field.kind.option.FACT.label": "事實",
  "review.personal-agent.memory-review.field.kind.option.CLAIM.label": "主張",
  "review.personal-agent.memory-review.field.kind.option.EXPERIENCE.label": "經驗",
  "review.personal-agent.memory-review.field.kind.option.PRACTICE.label": "實務",
  "review.personal-agent.memory-review.field.summary.label": "摘要",
  "review.personal-agent.memory-review.action.save.label": "儲存編輯",
  "review.personal-agent.memory-review.action.accept.label": "接受",
  "review.personal-agent.memory-review.action.reject.label": "拒絕",
  "navigation.enterprise-agent.nav.label": "個人代理",
  "page.enterprise-agent.home.title": "個人代理",
  "page.enterprise-agent.setup.title": "個人代理設定",
  "chat.enterprise-agent.home.composer.placeholder": "詢問問題或描述任務",
  "chat.enterprise-agent.home.composer.sendLabel": "傳送",
  "chat.enterprise-agent.home.context.label": "目前內容環境",
  "chat.enterprise-agent.home.context.selector.ariaLabel": "選擇內容環境",
  "chat.enterprise-agent.home.readiness.ready.label": "就緒",
  "chat.enterprise-agent.home.readiness.ready.message": "個人代理已就緒。",
  "chat.enterprise-agent.home.readiness.setup-required.label": "需要設定",
  "chat.enterprise-agent.home.readiness.setup-required.message": "使用個人代理前，請先完成 Provider 設定。",
  "chat.enterprise-agent.home.readiness.degraded.label": "效能下降",
  "chat.enterprise-agent.home.readiness.degraded.message": "目前 LLM Provider 處於降級狀態。",
  "chat.enterprise-agent.home.readiness.unavailable.label": "無法使用",
  "chat.enterprise-agent.home.readiness.unavailable.message": "目前 LLM Provider 無法使用。",
  "chat.enterprise-agent.home.action.open-setup.label": "開啟設定",
  "chat.enterprise-agent.home.empty.title": "我可以幫你做什麼？",
  "chat.enterprise-agent.home.empty.description": "我可以查看可用應用與內容環境、說明目前情況，並準備意見或方案。",
  "chat.enterprise-agent.home.suggestion.attention.label": "現在有哪些事情需要我關注？",
  "chat.enterprise-agent.home.suggestion.context.label": "說明我目前的內容環境",
  "setup.personal-agent.setup.title": "個人代理設定",
  "setup.personal-agent.setup.description": "完成由平台管理的 Provider 必要步驟。個人代理本身不保存 Provider 憑證。",
  "setup.personal-agent.setup.step.provider.title": "LLM Provider",
  "setup.personal-agent.setup.step.provider.description": "為 llm.inference 選擇或安裝 Provider。",
  "setup.personal-agent.setup.step.provider.status.current": "必要",
  "setup.personal-agent.setup.step.provider.status.complete": "完成",
  "setup.personal-agent.setup.step.provider.status.pending": "等待",
  "setup.personal-agent.setup.step.credentials.title": "Provider 設定",
  "setup.personal-agent.setup.step.credentials.description": "在 Provider 自己的設定介面配置憑證與執行參數。",
  "setup.personal-agent.setup.step.credentials.status.current": "必要",
  "setup.personal-agent.setup.step.credentials.status.complete": "完成",
  "setup.personal-agent.setup.step.credentials.status.pending": "等待",
  "setup.personal-agent.setup.step.credentials.status.blocked": "等待",
  "setup.personal-agent.setup.step.readiness.title": "Provider 就緒狀態",
  "setup.personal-agent.setup.step.readiness.description": "Host 會驗證 Provider 解析結果與執行階段是否可用。",
  "setup.personal-agent.setup.step.readiness.status.current": "檢查中",
  "setup.personal-agent.setup.step.readiness.status.complete": "完成",
  "setup.personal-agent.setup.step.readiness.status.blocked": "等待",
  "setup.personal-agent.setup.step.readiness.status.error": "需要處理",
  "setup.personal-agent.setup.step.ready.title": "就緒",
  "setup.personal-agent.setup.step.ready.description": "個人代理現在可以使用已選擇的 LLM Provider。",
  "setup.personal-agent.setup.step.ready.status.complete": "完成",
  "setup.personal-agent.setup.step.ready.status.blocked": "等待",
  "setup.personal-agent.setup.action.choose-provider.label": "選擇 Provider",
  "setup.personal-agent.setup.action.open-provider-catalog.label": "開啟 Provider 目錄",
  "setup.personal-agent.setup.action.configure-provider.label": "設定 Provider",
  "setup.personal-agent.setup.action.open-agent.label": "開啟個人代理",
  "setup.personal-agent.setup.action.provider-status.label": "Provider 狀態",
  "setup.personal-agent.setup.action.check-provider-status.label": "檢查 Provider 狀態",
  "setup.personal-agent.setup.action.recheck-setup.label": "重新檢查設定",
  "setup.personal-agent.setup.action.review-memory.label": "審核記憶",
  "setup.personal-agent.setup.action.memory-governance.label": "記憶治理",
  "setup.personal-agent.setup.action.memory-source-health.label": "記憶來源健康狀態",
  "setup.personal-agent.setup.action.agent-quality.label": "個人代理品質"
};

export const enterpriseAgentPackage: PackageManifestV010 = {
  contractVersion: "0.1.0",
  packageId: ENTERPRISE_AGENT_PACKAGE_ID,
  displayName: "Personal Agent",
  version: "0.1.0",
  type: "AGENT",
  features: [
    {
      contractVersion: "0.1.0",
      featureId: ENTERPRISE_AGENT_FEATURE_ID,
      packageId: ENTERPRISE_AGENT_PACKAGE_ID,
      version: "0.1.0",
      activationScope: "INSTALLATION",
      defaultActivation: true,
      providesCapabilities: [
        "agent.personal",
        "agent.personal.tool-discovery",
        "agent.enterprise",
        "agent.enterprise.app-manager-tools",
        "agent.enterprise.tool-discovery"
      ],
      contributions: [
        {
          kind: "eidos.experience",
          manifest: {
            contractVersion: "0.1.0",
            experienceId: "enterprise-agent",
            packageId: ENTERPRISE_AGENT_PACKAGE_ID,
            featureId: ENTERPRISE_AGENT_FEATURE_ID,
            defaultRoute: "/enterprise-agent",
            pages: [
              {
                id: "enterprise-agent.home",
                title: "Personal Agent",
                source: ENTERPRISE_AGENT_PAGE_SOURCE
              },
              {
                id: "enterprise-agent.setup",
                title: "Personal Agent setup",
                source: ENTERPRISE_AGENT_SETUP_PAGE_SOURCE
              },
              {
                id: "enterprise-agent.memory-review",
                title: "Memory review",
                source: ENTERPRISE_AGENT_MEMORY_REVIEW_PAGE_SOURCE
              },
              {
                id: "enterprise-agent.quality",
                title: "Personal Agent quality",
                source: ENTERPRISE_AGENT_QUALITY_PAGE_SOURCE
              },
              {
                id: "enterprise-agent.quality-review",
                title: "Personal Agent quality review",
                source: ENTERPRISE_AGENT_QUALITY_REVIEW_PAGE_SOURCE
              }
            ],
            routes: [
              {
                id: "enterprise-agent.home",
                path: "/enterprise-agent",
                pageId: "enterprise-agent.home"
              },
              {
                id: "enterprise-agent.setup",
                path: "/enterprise-agent/setup",
                pageId: "enterprise-agent.setup"
              },
              {
                id: "enterprise-agent.memory-review",
                path: "/enterprise-agent/memory",
                pageId: "enterprise-agent.memory-review"
              },
              {
                id: "enterprise-agent.quality",
                path: "/enterprise-agent/quality",
                pageId: "enterprise-agent.quality"
              },
              {
                id: "enterprise-agent.quality-review",
                path: "/enterprise-agent/quality/review",
                pageId: "enterprise-agent.quality-review"
              }
            ],
            navigation: [
              {
                id: "enterprise-agent.nav",
                label: "Personal Agent",
                route: "/enterprise-agent",
                order: 10
              }
            ]
          }
        },
        {
          kind: "eidos.workbench-activity",
          activity: {
            contractVersion: "0.1.0",
            id: "enterprise-agent",
            title: "Personal Agent",
            icon: "agent",
            kind: "side-route",
            route: "/enterprise-agent",
            order: 20,
            localization: {
              namespace: ENTERPRISE_AGENT_PACKAGE_ID,
              key: "workbench.activity.label"
            }
          }
        },
        ...([
          ["en", enMessages],
          ["zh-CN", zhCnMessages],
          ["ja", jaMessages],
          ["zh-TW", zhTwMessages]
        ] as const).map(([locale, messages]) => ({
          kind: "eidos.localization-bundle" as const,
          bundle: {
            contractVersion: "0.1.0" as const,
            namespace: ENTERPRISE_AGENT_PACKAGE_ID,
            locale,
            messages
          }
        }))
      ]
    }
  ]
};

export const enterpriseAgentExperienceAssets = new Map<string, unknown>([
  [ENTERPRISE_AGENT_PAGE_SOURCE, {
    contractVersion: "0.1.0",
    kind: "chat",
    id: "enterprise-agent.home",
    title: "Personal Agent",
    command: {
      code: "enterprise-agent.chat",
      inputVersion: "0.1.0"
    },
    composer: {
      key: "message",
      placeholder: "Tell Personal Agent what you want to accomplish",
      sendLabel: "Send"
    },
    emptyState: "Ask Personal Agent to inspect, explain or prepare an opinion or change.",
    metadata: {
      packageId: ENTERPRISE_AGENT_PACKAGE_ID,
      featureId: ENTERPRISE_AGENT_FEATURE_ID,
      convergence: {
        historicalProject: "Experience Compiler (EC)",
        sourceRepository: "jiangxng/Experience-Compiler",
        sourceRelease: "1.0.1",
        targetIdentity: "Personal Agent"
      },
      llm: {
        requiredCapability: "llm.inference",
        integrationStatus: "PROVIDER_RESOLVED_AT_RUNTIME"
      },
      preservedAssets: [
        "knowledge",
        "memory",
        "learning",
        "research",
        "context-compiler",
        "provenance-lineage",
        "industry-packs",
        "model-replacement"
      ]
    }
  }]
]);
