export {
  EOG_2D_PACKAGE_ID as EOG_2D_VIEWER_PACKAGE_ID,
  EOG_2D_VIEWER_FEATURE_ID,
  EOG_2D_VIEWER_CAPABILITY,
  EOG_2D_VIEWER_EXPERIENCE_ID,
  EOG_2D_VIEWER_WORKSPACE_PAGE_ID,
  EOG_2D_VIEWER_WORKSPACE_PAGE_SOURCE,
  EOG_2D_VIEWER_WORKSPACE_ROUTE,
  EOG_2D_VIEWER_WORKSPACE_GET_ACTION,
  EOG_2D_VIEWER_WORKSPACE_SELECTION_GET_ACTION,
  EOG_2D_VIEWER_TEMPLATE_PREVIEW_PAGE_ID,
  EOG_2D_VIEWER_TEMPLATE_PREVIEW_PAGE_SOURCE,
  EOG_2D_VIEWER_TEMPLATE_PREVIEW_ROUTE,
  EOG_2D_VIEWER_TEMPLATE_PREVIEW_GET_ACTION,
  EOG_2D_VIEWER_TEMPLATE_PREVIEW_SELECTION_GET_ACTION,
  EOG_2D_VIEWER_DEFINITION_PREVIEW_PAGE_ID,
  EOG_2D_VIEWER_DEFINITION_PREVIEW_PAGE_SOURCE,
  EOG_2D_VIEWER_DEFINITION_PREVIEW_ROUTE,
  EOG_2D_VIEWER_DEFINITION_PREVIEW_GET_ACTION,
  EOG_2D_VIEWER_DEFINITION_PREVIEW_SELECTION_GET_ACTION,
  eog2dPackage as eog2dViewerPackage
} from "../eog-2d/package.js";

/**
 * Legacy Observatory names remain import-compatible while ownership moves to
 * the peer Enterprise Observatory package.
 */
export {
  ENTERPRISE_OBSERVATORY_2D_PAGE_ID as EOG_2D_VIEWER_PAGE_ID,
  ENTERPRISE_OBSERVATORY_MOBILE_PAGE_ID as EOG_2D_VIEWER_MOBILE_PAGE_ID,
  ENTERPRISE_OBSERVATORY_2D_PAGE_SOURCE as EOG_2D_VIEWER_PAGE_SOURCE,
  ENTERPRISE_OBSERVATORY_MOBILE_PAGE_SOURCE as EOG_2D_VIEWER_MOBILE_PAGE_SOURCE,
  ENTERPRISE_OBSERVATORY_2D_ROUTE as EOG_2D_VIEWER_ROUTE,
  ENTERPRISE_OBSERVATORY_MOBILE_ROUTE as EOG_2D_VIEWER_MOBILE_ROUTE
} from "../enterprise-observatory/package.js";
