export {
  EOG_2D_PACKAGE_ID as EOG_2D_VIEWER_PACKAGE_ID,
  EOG_2D_VIEWER_FEATURE_ID,
  EOG_2D_VIEWER_CAPABILITY,
  EOG_2D_VIEWER_EXPERIENCE_ID,
  EOG_2D_VIEWER_WORKSPACE_PAGE_ID,
  EOG_2D_VIEWER_WORKSPACE_PAGE_SOURCE,
  EOG_2D_VIEWER_WORKSPACE_ROUTE,
  EOG_2D_VIEWER_PAGE_ID,
  EOG_2D_VIEWER_MOBILE_PAGE_ID,
  EOG_2D_VIEWER_PAGE_SOURCE,
  EOG_2D_VIEWER_MOBILE_PAGE_SOURCE,
  EOG_2D_VIEWER_ROUTE,
  EOG_2D_VIEWER_MOBILE_ROUTE,
  eog2dPackage as eog2dViewerPackage
} from "../eog-2d/package.js";
